[#4496] Fix locking in partial indexes
Upstream commit ID : fb-mysql-5.6.35/63ab55f35f9780ecef55dcba8b36475f5c4cb073
PS-7921 : Merge percona-202105

Summary:
Fix a race condition during deletes in partial indexes. Currently we're not locking the prefix during deletes, which means that we could end up materializing deleted rows. For example, if we have:
1. T1 deletes a row A without committing
2. T2 reads row A during materialization, and generates SK for row A
3. T1 commits
4. T2 commits

Then the partial index will contain an extra row that shouldn't exist.

The solution is to also add locking there (similar to insert path).

Fix the stress test to catch this case, since previously, it was not surfacing errors correctly.

Also, create a new iterator object during materialization, since it is possible that the old iterator may be on an old superversion, and may not see all keys.

Reviewed By: hermanlee

Differential Revision: D29683427

fbshipit-source-id: ad8c1b7d4e9

==========================================

[#5576] Fix flaky rocksdb.partial_index_stress MTR

Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/c1f79a85e126
PS-9395: Merge percona-202401 (https://jira.percona.com/browse/PS-9395)

Summary:
sometime rocksdb.partial_index_stress MTR fail especially under myrocks DD due
```
MySQLdb._exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction (snapshot conflict)')
```

From https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html, SET SESSION TRANSACTION doesn't apply to cur trx.

The fix is to commit Isolation change first to avoid snapshot conflict during first insert

Differential Revision: D50420444