[#2551] PS-3890: Native Partitioning for TokuDB and RocksDB for 8.0
partition_base.* are copied from ha_partition.* in 5.7 with corresponding fixes.

5.7 required some additional code to read partition info from .frm files, in
8.0 this functionality is not required, the corresponding code was removed.

Currently "inline alter partition" and "exchange partition" are not implemented.

As "inline alter partition" is not implemented, all "alter partition" operations
involve full table copying. There can be such errors as "no partition found"
duriring copying, which must be ignored, what is also implemented in the server
code.

The warning is added on alter partitioning to notify that inplace partition
altering is not supported.

The following test results were rewritten due to new warning:

rocksdb      partition
tokudb.bugs  alter_part_tokudb_bug_155
tokudb.parts partition_mgm_lc10_tokudb partition_special_tokudb
             partition_alter3_tokudb part_supported_sql_func_tokudb

Testcase for http://bugs.mysql.com/bug.php?id=71270 was ported from 5.7. See
bug71270.* files.
==========================================
PS-4212 : 8.0 : Fix various places where macros are redefined or used when undefined PS-421

Original title:
PS-4212 : 8.0 : Fix various places where macros are redefined or used when undefined PS-4213 : 8.0 : Fix -Wunused-parameter PS-4214 : 8.0 : Fix -Wsuggest-attribute=format

PS-4213 : 8.0 : Fix -Wunused-parameter
PS-4214 : 8.0 : Fix -Wsuggest-attribute=format

- RocksDB (not Myrocks) has several cases of using undefined macros
  (#if SOMEMACRO).  We don't have any direct control over RocksDB so report
  upstream and loosen the error until such time it is fixed.

- RocksDB (not MyRocks) has hundreds of cases of unused parameters.  We don't
  have any direct control over RocksDB so report upstream and loosen the error
  until such time it is fixed.

- RocksDB (not MyRocks) has a few of cases of variadic format functions which
  are not annotated with attribute 'format.  We don't have any direct control
  over RocksDB so report upstream and loosen the error until such time it is
  fixed.
==========================================
PS-4249 : 8.0 : 8.0 MyRocks plugin needs to link to libregex.a

- Added regex to link libraries
==========================================
[#2611] Post-push fix for for PS-3890: add 'override' specifier for Partition_base descenda

Original title:
[#2611] Post-push fix for for PS-3890: add 'override' specifier for Partition_base descendants and remove HA_CREATE_INFO object clearing with memset().

Unused ha_tokupart::bas_ext() was also removed.
==========================================
[#2638] PS-269 (Initial Percona Server 8.0.12 tree)

Remove explicit server system variable settings from MyRocks tests
where they matched the new 8.0 defaults.
==========================================
[#2640] PS-4918 : debug assertion on 8.0 upgrade of TokuDB tables created with explicit ROW

Original title:
[#2640] PS-4918 : debug assertion on 8.0 upgrade of TokuDB tables created with explicit ROW_FORMAT

- On table upgrade and conversion from .frm to DD, detect use of TokuDB
  ROW_FORMAT specifiers and reset table row_format to default.

- Refactored mtr upgrade testing from native partitioning to be a bit more
  generic and usable for other type of simple upgrade scenario testing.

- Fixed up TokuDB and RocksDB partition testing to use newly refactored/generic
  upgrade test components, re-recorded for minor differences in result.

- Implemented TokuDB row format upgrade test and added upgrade seed datadir.added upgrade
==========================================
[#2678] PS-4859 : UBSAN storage/rocksdb/rocksdb/util/coding.h:384:3: runtime error: load of

Original title:
[#2678] PS-4859 : UBSAN storage/rocksdb/rocksdb/util/coding.h:384:3: runtime error: load of misaligned address PS-4860 : UBSAN storage/rocksdb/rocksdb/util/coding.h:367:3: runtime error: store to misaligned address

PS-4860 : UBSAN storage/rocksdb/rocksdb/util/coding.h:367:3: runtime error: store to misaligned address

- Upstream RocksDB actually has this mostly handled when building stand alone.
  The problem is that MyRocks does not build RocksDB as a subproject, instead it
  'sources' the files directly into the MyRocks compilation module.  By doing
  this, the CMakeLists.txt magic that sets up RocksDB for UBSAN runs within
  the RocksDB project is never invoked.  The fix is to copy some of the logic
  from within the RocksDB CMakeLists.txt into the MyRocks CMakeLists.txt.
==========================================
[#2693] PS-269 (Initial Percona Server 8.0.12 tree)

MyRocks: remove GCC version check because MySQL allowed minimum
version is higher in 8.0.

==========================================

[#4732] WDCZEN-35 fix: Adapt rocksdb.upgrade_parts_from_prev_ver to ZenFS environment

https://jira.percona.com/browse/WDCZEN-35

'rocksdb.upgrade_parts_from_prev_ver' MTR test case adapted to the ZenFS
environment.

==========================================

PS-5363 (Merge MySQL 8.0.17): RocksDB fixes

- Commit e4148f2a22922687f7652c4e3d21a22da07c9e78 alters PSI rwlock interface,
  bumps version and deprecates prior interface.  This breaks PerconaFT
  portability layer.  Added #ifdef on PSI_CURRENT_RWLOCK_VERSION to compile to
  appropriate interface for unlock_rwlock.  Advanced git submodule commit
  pointer for PerconaFT.

- Commit 6e424cee06fb6d0d1b989c9b9c5bc3f03d0c1809 adds new pure virtual method
  to common Partition_handler which now forces ha_tokupart and ha_rockspart to
  implement same functionality.

- Commit cfef76864b1300701733766ea05ca4ec55c6e647 changes interface of
  create_temp_file to add new enum to indicate to unlink on close or not.  This
  is called from Rdb_index_merge::merge_file_create.  Fixed the call to use the
  new interface.

- Commit 5001463b65492f3bd499fc2abcd9c16e30be09bd removes remaining "C Legacy"
  alloc_root from my_alloc.h.  Code using alloc_root in "C" changed to use C++
  interface of MEM_ROOT.

- Reformatting during the 8.0.17 merge introduced a typo in my_base.h that
  incorrectly addes a trailing "/" which causes compilation error when
  HA_ERR_DEST_SCHEMA_NOT_EXIST is used.

- Commit 84055756911803a724afa8ebd58859393347c7e4 introduces support for
  multi-value indexes for InnoDB but also introduces a new MySQL data type
  MYSQL_TYPE_TYPED_ARRAY.  TokuDB and MyRocks will NOT support this immediately.
  There are various switch statements which cover all MySQL data types that are
  fixed to recognize this new type.

- Commit 029504b7f32beb324ed725bc03aac8597c6d840e now causes assertions due to
  MyRocks errors being in the 'server' range and not the 'client' range.
  PS 8.0.17 merge handled errmsg-utf8.txt slightly incorrectly.  Range
  50000-51999 are specifically reserved for Facebook 'client' error messages by
  Oracle at Facebooks request and is where these errors belong.  Unfortunately,
  the logic that checks and asserts on the 'client' error message being in the
  'server' space does not account for this.  Percona Server fix is to introduce
  a Percona Server/MyRocks range of errors within the client range and relocate
  the MyRocks client codes there.

- MTR issues:
  - mtr does not support suite names with '.' in the name.  Suites have been
    renamed to use '_' instead.  Various mtr tests were using
    `–source <suite>/include/<someinclude.inc>` instead of
    `../include/<someinclude.inc>, these were fixed.

  - New warnings where tests either needed fixing and/or re-recording:
    - Warning  1681  Integer display width is deprecated and will be removed in
      a future release.
    - Warning  1681  The ZEROFILL attribute is deprecated and will be removed in
      a future release. Use the LPAD function to zero-pad numbers, or store the
      formatted numbers in a CHAR column
    - Warning  1681  Specifying number of digits for floating point data types
      is deprecated and will be removed in a future release.
    - Warning  1287  '&&' is deprecated and will be removed in a future release.
      Please use AND instead
    - Warning  1287  'BINARY as attribute of a type' is deprecated and will be
      removed in a future release. Please use a CHARACTER SET clause with _bin
      collation instead
    - Warning  3719  'utf8' is currently an alias for the character set UTF8MB3,
      but will be an alias for UTF8MB4 in a future release. Please consider
      using UTF8MB4 in order to be unambiguous.
    - Warning  3856  AUTO_INCREMENT support for FLOAT/DOUBLE columns is
      deprecated and will be removed in a future release. Consider removing
      AUTO_INCREMENT from column 'C1'
    - Warning  1287  SQL_CALC_FOUND_ROWS is deprecated and will be removed in a
      future release. Consider using two separate queries instead.
    - Warning  1287  FOUND_ROWS() is deprecated and will be removed in a future
      release. Consider using COUNT(*) instead.

  - SHOW CREATE TABLE outputs different now due to exposing ENCRYPTION=Y|N and
    tests need re-recorded.

  - Changes to optimizer and EXPLAIN output.

  - Changes to Warnings from SHOW WARNINGS.

  - Changes to mysqldump output.

  - Fix test(s) with non-deterministic ordering output by using --sorted_result
    to avoid influencing optimizer plan.

  - Commit 5eef3b35da3ef2ada74dd53f6b04252523706b7f changes common rpl test
    rpl_insert_id and forces re-record of tests that include it.

  - Commit c7934d119aeb00779d8ad2d3234987c1fbab3519 adds new NO PAD collation
    for utf8mb4 and forces some tests that enumerate and act on collations to be
    re-recorded.

  - Commit ef6b616aad51ba15fcb24e3fd16f54495f321d6b bumped HA_ERR_LAST causing
    handler HA_* error numbers to change, forcing mtr re-records.

  - Commit commit/3c19b5f98c47541ed20992f08eafdf40ca19f3db changes behavior of
    conversion of double to timestamp which in turn causes FROM_UNIXTIME() to
    return NULL instead of inaccurate timestamp.  Some tests need re-recording
    to observe this new behavior.

  - Unidentifiable change to processlist states on a SELECT * ... FOR UPDATE
    changes the state that several wait_condition need to wait on from "Sending
    data" to "executing"

==========================================

[#3094] PS-5206 : [PS8QA] handle_fatal_signal (sig=11) in handler::get_ha_share_ptr

Problem:
-------
Server crashes when ha_tokupart::clone() interface is used.

Fix:
----
To clone native partition tokupart handler, we will not use clone()
on each partition handler. This is because tokudb_create_handler() gives
ha_tokupart handler instead of ha_tokudb handlers. This happens becuase of
presence of parition info in TABLE_SHARE

We create a new partition handler in clone() with part_info from the current
handler.

Note that problem is exactly same for rocksdb as well and the same fix
applies.

==========================================

[#3489] Implemented PS-5532 (Merge MySQL 5.7.27) (docs)

https://jira.percona.com/browse/PS-5532

***
Updated man pages from MySQL Server 5.7.27 source tarball.

***
Updated 'scripts/fill_help_tables.sql' from MySQL Server 5.7.27 source
tarball.

==========================================

[#5221] Implemented PS-8979 (Merge MySQL 8.2.0) (conflicts solved: mysql-test)

https://jira.percona.com/browse/PS-8979

Absorbed into this commit: mysql-test/suite/rocksdb/t/index_merge_rocksdb2-master.opt