[#4362] Return stats from storage engine directly without table open
Upstream commit ID : fb-mysql-5.6.35/18d7f5ba8304c3bf470b8fc27de601eafe467910
PS-7731 : Merge percona-202102

Summary:
In 8.0 query from i_s.tables are *much* slower (~5x) most likely due to table open/close are much slower - profiling data showed that 74% time spent on opening tables and 19.71% time spent on reading histograms, only 2.41% spent on the actual stats inside MyRocks.

8.0 provides a new callback get_table_statistics and get_index_column_cardinality that when "overridden", signal MySQL to go call those functions to fill in stats directly, which should be much faster, with some caveats:
* Our stats code path need to work without table open - this fix updates our stat code path to strictly use Rdb_tbl_def and Rdb_key_def.

One catch is that we won't be able to update the auto_inc value correctly because we won't know if the table actually has AUTO_INCREMENT without opening it, so there are some corner cases the value might be NULL (such as immediately after creating a table with AUTO_INCREMENT). This actually aligns with ROCKSDB_DDL table behavior and InnoDB behavior as well. Once you open the table, the cached Rdb_tbl_def::m_auto_inc_val should be updated properly.

* We also need to make sure the lifetime / locking works properly with regarding to DDL and special cases like drop cf.

Fortunately the table_stats code path does take MDL_EXPLICIT lock with the db_name.table_name, so correctness should be straight-forward. One special case if DROP TABLE is running at the same time, the MDL_EXPLICIT lock may succeed *after* drop table succeed, and Rdbl_ddl_manager::find would return null, and we would give default values in the columns and with a error message saying table cannot be found.

Note this version only overrides get_table_statistics (and it updates SQL layer to treat them separately) and we can add get_index_column_cardinality in the future if there is a need - right now there is little evidence that we are querying information_schema.statistics much (if not at all).

Reviewed By: hermanlee

Differential Revision: D26624028

fbshipit-source-id: 3b41f25d61c

==========================================

[#4362] Fix rows_read and queries_range stats in bypass

Upstream commit ID : fb-mysql-5.6.35/50bfa5b89b2240eb84ad81f6c0e90bf8e0cbae60
PS-7767 : Merge percona-202103

Summary:
Bypass updates rows_sent and rows_examined but didn't update rows_read. This fixes that and adds tests. We also get rocksdb_queries_point and rocksdb_queries_range for free as we are using MyRocks API to access data. Note I didn't include rows_examined in the test because querying unrelated information_schema tables will affect rows_examined and it is kinda flaky depending on many factors like perf schema. I did found a double counting issue with rocksdb_queries_range and fixed it as well.

Reference Patch: https://github.com/facebook/mysql-5.6/commit/6106eba3fe767bd007e64975bfd52722b0ca9987

----
Porting Notes: Removed updates to table stats which is not ported to 8.0.

Differential Revision: D25809584

fbshipit-source-id: 4cbb31e5b35

==========================================

[#4362] Refactoring index covering check to match MyRocks and add non-covering SK tests and

Original title:
[#4362] Refactoring index covering check to match MyRocks and add non-covering SK tests and rocksdb_covering_secondary_key stats

Upstream commit ID : fb-mysql-5.6.35/7194dfd7679aa70bda91236d0d6455d5324e615b
PS-7731 : Merge percona-202102

Summary:
When considering when a secondary key is covering, we need to also consider lookup bitmap for some special cases like using covering bitmap w/ prefix keys. This isn't much of an issue with 5.6 today because we don't actually enable covering bitmap format in prod but in 8.0 it might be an issue. Either way this refactors the covering check to be exactly the same as MyRocks does. Also adds more tests for covering / non covering prefix tests.

Also in order to catch cases where we incorrectly consider covering secondary keys to be non-covering, I've added rocksdb_covering_secondary_key_count support into bypass (should've done that earlier) and added checks in secondary range key tests to ensure covering check is done correctly.

Reference Patch: https://github.com/facebook/mysql-5.6/commit/30e9039c7cc8aa1162b2570b4e13e3a5c7e7d374

----

Porting Notes:
* Fixed an issue that we need to explicitly compare with Rdb_key_def::KEY_COVERED
* The scenario with prefix key is now correctly handled and re-enabled in bypass_select_scenarios.inc

Reviewed By: Pushapgl

Differential Revision: D26566848

fbshipit-source-id: f149f119da4

==========================================

[#4362] Fix buffer management issues during online alter

Upstream commit ID : fb-mysql-5.6.35/edce7e9f7518a0a9159a2cf5c63e8e8f340a0481
PS-7731 : Merge percona-202102

Summary:
This fixes two issues related to online alter found by the rocksdb.rqg_runtime test.

1. A buffer overflow would happen occasionally, and this was caused by the fact that if an online alter fails for whatever reason (eg. duplicate key error), then we never restore the old buffer from the old schema, and if the old buffers were larger than the new buffers, you could run into buffer overflow in later queries. The fix is to reallocate the old buffers.
2. Memory allocated for holding blobs was sometimes leaked during online alter. This is because in `Rdb_key_def::unpack_record`, the blob is allocated from the handler on the `TABLE` object passed in, and this is usually usually the correct handler (ie. `table->file` matches the handler object that called the unpack function). However, during online alter, we pass in `altered_table` instead, so the buffer ends up being allocated on `altered_table->file`. That handler object was never opened with `ha_rocksdb::open`, so it never gets closed and the buffer leaks. To fix this, call we free the buffers after online alter.

Reviewed By: Pushapgl

Differential Revision: D26891145

fbshipit-source-id: 2a38e485cd1

==========================================

[#5031] Revert "Skip costing group by plans for empty tables"

Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/6e0da3ee79c423a142a8bdbd80196a1e9b6585df
PS-8494: Merge percona-202205 (https://jira.percona.com/browse/PS-8494)

Summary:
It turns out that division by zero on empty tables is a problem specific
to MyRocks. It turns out that storage engines that don't support
HA_STATS_RECORDS_IS_EXACT should never return 0 for number of records.
Otherwise, the SQL layer may assume that the table is empty and elide
reading from it, which would be incorrect if the table actually
contained data.

This is indicated in this comment:

  /*
    The number of records in the table.
      0    - means the table has exactly 0 rows
    other  - if (table_flags() & HA_STATS_RECORDS_IS_EXACT)
               the value is the exact number of records in the table
             else
               it is an estimate
  */
  ha_rows records;

To fix, copy InnoDB's behaviour and always return >= 1.

Squash with: D35825006

Reviewed By: luqun

Differential Revision: D37399246

fbshipit-source-id: 0185b05a2c0e2cfcd3fdbb89f0aec6052ecfede5

==========================================

[#5031] bad my_error usage causing crash during rocksdb_get_table_statistics

Summary:
in rocksdb_get_table_statistics(), the call ha_rocksdb::update_stats(stats, tbl_def) may return HA_EXIT_FAILURE(value is 1) if some error occurs.

The error message for error code 1 is "Can't create/write to file '%s' (OS errno %d - %s)" and suppose to passing 3 argument for this format string, and now there is only 1 valid argument passed and during runtime, it will try to fetch remaining values through address/register, which cause crash(SIGSEGV).

the change is to use ER_INTERNAL_ERROR instead of return code from ha_rocksdb::update_stats.

The error message for ER_INTERNAL_ERROR is "Internal error: %s".

crash call stack:
```
handle_fatal_signal()
__strlen_evex ()
__vfprintf_internal ()
__vsnprintf_internal ()
vsnprintf ()
my_error ()
myrocks::rocksdb_get_table_statistics()
dd::info_schema::Table_statistics::read_stat_from_SE()
```

Reviewed By: Pushapgl

Differential Revision: D37769523

fbshipit-source-id: f4a06f65f6f5727d4199a889730ff255ea3a537c

==========================================

[#4785] Don't blindly update auto_inc_val in update_stats when called from ha_rocksdb::info

Upstream commit ID : fb-mysql-5.6.35/fe90491c4fb92f620fc88f96c38d27a8797a20f1
PS-8216 : Merge percona-202108

Summary:
Previously in order to speed up i_s.tables I did some refactoring that moves some stats updates into storage engine to skip table open for better performance. But as a part of that refactoring we would always update auto_inc_val in ha_rocksdb::info(HA_STATUS_AUTO) which is expensive as it does a RocksDB Get, while the value is already in tbl_def::m_auto_inc_val.

This adds a flag to skip the auto_inc_val retrieval if called from ha_rocksdb::info, and let ha_rocksdb::info do the right thing by fetching from m_tbl_def directly which would have the correct value.

This should fix ~1.3% CPU in primaries.

Squash with: D26624028

Reviewed By: george-reynya

Differential Revision: D31366565

fbshipit-source-id: 4cdb37cc9b3

==========================================

[#5387] PS-9218: Merge MySQL 8.4.0 (fix terminology in replication tests)

https://perconadev.atlassian.net/browse/PS-9218

https://github.com/mysql/mysql-server/commit/44a77b5ba29994f8d3634b62c2825481574fc057

==========================================

[#5576] Fix MyRocks compilation under XCode 15 (#1364)

Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/83bb92de5a0a
PS-9395: Merge percona-202401 (https://jira.percona.com/browse/PS-9395)

Summary:
This fixes the errors listed below. For the array argument, fix by converting the arrays to pointers as this is what gets passed around anyway.
```
storage/rocksdb/rdb_datadic.cc:5528:9: error: format specifies type 'unsigned int' but the argument has type 'uint16_t' (aka 'unsigned short') [-Werror,-Wformat]
        index_info->m_index_dict_version, index_info->m_index_type,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
storage/rocksdb/rdb_datadic.cc:5528:43: error: format specifies type 'unsigned int' but the argument has type 'uchar' (aka 'unsigned char') [-Werror,-Wformat]
        index_info->m_index_dict_version, index_info->m_index_type,
                                          ^~~~~~~~~~~~~~~~~~~~~~~~
storage/rocksdb/rdb_datadic.cc:5529:9: error: format specifies type 'unsigned int' but the argument has type 'uint16_t' (aka 'unsigned short') [-Werror,-Wformat]
        index_info->m_kv_version, index_info->m_ttl_duration);
        ^~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

storage/rocksdb/ha_rocksdb.cc:14077:34: error: argument 'buf' of type 'uchar[8]' (aka 'unsigned char[8]') with mismatched bound [-Werror,-Warray-parameter]
    const Rdb_key_def &kd, uchar buf[Rdb_key_def::INDEX_NUMBER_SIZE * 2]) {
                                 ^
storage/rocksdb/./ha_rocksdb.h:406:64: note: previously declared as 'uchar[]' (aka 'unsigned char[]') here
  static rocksdb::Range get_range(const Rdb_key_def &kd, uchar buf[]);
                                                               ^
storage/rocksdb/ha_rocksdb.cc:14086:24: error: argument 'buf' of type 'uchar[8]' (aka 'unsigned char[8]') with mismatched bound [-Werror,-Warray-parameter]
    const int i, uchar buf[Rdb_key_def::INDEX_NUMBER_SIZE * 2]) const {
                       ^
storage/rocksdb/./ha_rocksdb.h:391:47: note: previously declared as 'uchar[]' (aka 'unsigned char[]') here
  rocksdb::Range get_range(const int i, uchar buf[]) const;
                                              ^
```

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1364

Differential Revision: D49440205

==========================================

[#5576] mysql on clang15: fix -Wformat errors

Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/797aaf807014
PS-9395: Merge percona-202401 (https://jira.percona.com/browse/PS-9395)

Summary:
clang 15 comes with a few extra [formatting warnings](https://clang.llvm.org/docs/DiagnosticsReference.html#wformat) that we treat as
errors. This diff fixes them in preparation for the upgrade.

Differential Revision: D51122375