[cmake] Fix gcc/clang build issues
[#3500] PS-6054: clang 5.0.1 reports "missing-braces" warnings

==========================================

[g7][#3504] PS-6057: Suppress gcc and clang warnings for RocksDB and TokuDB

==========================================

[#3528] PS-6058: gcc 5.5.0 compilation warnings for router

Fixed:
1.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc: In function ‘constexpr int o11x_version(TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc:99:57: error: expression ‘<throw-expression>’ is not a constant-expression
       throw std::invalid_argument("version out of range");
```
2.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc: In constructor ‘TlsServerContext::TlsServerContext(TlsVersion, TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc:67:43: error: statement has no effect [-Werror=unused-value]
   SSL_CTX_set_ecdh_auto(ssl_ctx_.get(), 1);
```

==========================================

[#360] Add FORTIFY_SOURCE=2 definition in cmake for release builds

==========================================

[split] build flag list whitespace (CMakeLists.txt)

Split out of the following commit, which bundled three unrelated
one-line post-merge fixes with three different owners:

[compilation] dCompilation/test fixes for 8.0.13 merge, #2

===============================================

[#2756] dCompilation/test fixes for 8.0.13 merge, #2

* Added a missing whitespace to a build flag list
* Fixed mtr test suite list
* Fixed a typo in a unit test

===============================================

[#2249] PS-3887: Move perfschema to the beginning of the storage list in CONFIGURE_PLUGINS

[#2133] PS-3793: added osx travis config

* Added OSX to the build matrix.
* Fixed issues with older bash versions on OSX.
* Made maintainer_mode optional, as the OSX build results in some warnings, and fixing them would take time.
  As it's not an officially supported platform, warnings are ok for now.
* Made tokudb optional, as the OSX build doesn't support it

(cherry picked from commit 185b61405d80a6c8af12081a1e42677299746b74)
(cherry picked from commit 64cfbf3b99c337a8ffdd39641a1efeda4db95726)

======================================================================

[#2240] PS-3899: silence an uninitialized read in zlib

According to the library developers, this is an optimization which while reads these bytes, doesn't use them for anything, and should be ignored.

(cherry picked from commit 2096be4b643e2047fa33c2dbd12c73d820fdae18)
(cherry picked from commit 43f99a0eacd2a6e0271482d79e544c9d518268d6)

==========================================

[g8]PS-5363 (Merge MySQL 8.0.17): added missing parameter in MY_SANITIZER_CHECK for MSAN

==========================================

[#2075] lp-1738171: Show compiler output when the ABI check fails

Changes in do_abi_check.cmake were made to have the ability to see
compilator output on compilation error.

Split out of "[#2075] lp-1738171: Build error on FreeBSD with 5.6.38-83.0".

(cherry picked from commit cf8bfa4ef1fcd90596cdcfda1146231cd2e8a124)