[#3500] PS-6054: clang 5.0.1 reports "missing-braces" warnings
==========================================

[g7][#3504] PS-6057: Suppress gcc and clang warnings for RocksDB and TokuDB

==========================================

[#3528] PS-6058: gcc 5.5.0 compilation warnings for router

Fixed:
1.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc: In function ‘constexpr int o11x_version(TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc:99:57: error: expression ‘<throw-expression>’ is not a constant-expression
       throw std::invalid_argument("version out of range");
```
2.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc: In constructor ‘TlsServerContext::TlsServerContext(TlsVersion, TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc:67:43: error: statement has no effect [-Werror=unused-value]
   SSL_CTX_set_ecdh_auto(ssl_ctx_.get(), 1);
```