[unittest] Fix compiler warnings, VIO mock signature and sanitizer linking
==========================================

[unittest] PS-8166 feature: Add support for Ubuntu 22.04 Jammy Jellyfish (clang-14 fix

Original title:
[clang14_build] PS-8166 feature: Add support for Ubuntu 22.04 Jammy Jellyfish (clang-14 fixes)

https://jira.percona.com/browse/PS-8166

Fixed 'clang-14' compilation issues for both 'Debug' and
'RelWithDebInfo' configurations.

==========================================

[#4769] PS-8166 feature: Add support for Ubuntu 22.04 Jammy Jellyfish (OpenSSL 3.0.x suppor

Original title:
[#4769] PS-8166 feature: Add support for Ubuntu 22.04 Jammy Jellyfish (OpenSSL 3.0.x support)

https://jira.percona.com/browse/PS-8166

Applied OpenSSL 3.0.x ('ssl3') patch from 'mysql-server-8.0' Ubuntu 22.04
Jammy Jellyfish source package.

==========================================

Revert "PS-7694: Fix compilation issues with gcc and clang"

This reverts commit 5e2d7a99b2e87cb953b8cfe72b445e30a9838cfc.

==========================================

[final-parity] include/my_alloc.h: include <cstdint> for std::uintptr_t used by
MEM_ROOT::Alloc_aligned(); storage/innobase/handler/i_s.cc: drop the
trailing blank line at end of file

==========================================

[#5105] PS-8880: Server option replication_sender_observe_commit_only is not honored for XA ROLLBACK

https://jira.percona.com/browse/PS-8880

Description
-----------
The server variable replication_sender_observe_commit_only is not
honored for XA ROLLBACK command because of the typo error in
https://github.com/mysql/mysql-server/blob/057f5c9509c6c9ea3ce3acdc619f3353c09e6ec6/sql/rpl_binlog_sender.cc#L134

=== TYPO BEGIN ===
            m_to_set = (strncmp("XA COMMIT", ev.query, 9) == 0) ||
                       (strncmp("XA ABORT", ev.query, 8) == 0) ||
                       (strncmp("COMMIT", ev.query, 6) == 0);
          break;
=== TYPO END ===

In the above code block, the command is compared against "XA ABORT", but
it is not a valid query in MySQL.

Solution
--------
Changed XA ABORT to XA ROLLBACK in the above block.

==========================================

[#5114] PS-8728 feature: Align Percona's Data Masking functionality with Oracle 8.0.33 (rem

Original title:
[#5114] PS-8728 feature: Align Percona's Data Masking functionality with Oracle 8.0.33 (removed ext namespace)

https://jira.percona.com/browse/PS-8728

As both Oracle MySQL Server and Percona Server for MySQL now compile sources
in c++17 mode, 'string_view' and 'optional' using declarations in the 'ext'
namespace (aliasing corresponding class templates from the 'boost' library)
are no longer needed. Instead we now use standard 'std::optional'
from the '<optional>' header and 'std::string_view' from the '<string_view>'
header.

Some direct usages of 'boost::optional' also changed to 'std::optional'.

==========================================

[#5221] Implemented PS-8979 (Merge MySQL 8.2.0) (conflicts solved: mysql-test)

https://jira.percona.com/browse/PS-8979

Absorbed into this commit: mysql-test/suite/perfschema/t/dd_version_check.test

==========================================

[#5221] Implemented PS-8979 (Merge MySQL 8.2.0) (conflicts solved: code)

https://jira.percona.com/browse/PS-8979

Absorbed into this commit: storage/ndb/test/ndbapi/test_event.cpp

==========================================

[squash] PS-8844: Set "-fvisibility-inlines-hidden" for all components

Absorbed into this commit: unittest/gunit/CMakeLists.txt

==========================================

[#5387] Implemented PS-9218 (Merge MySQL 8.4.0) (conflicts solved)

==========================================

[#5387] PS-9218: Merge MySQL 8.4.0 (fix gcc-14 build)

https://perconadev.atlassian.net/browse/PS-9218

==========================================

[#5400] PS-9328: Merge 8.4.2 - Revert fix for PS-9125 Fix gtid_next formatting in Gtid_spec

Original title:
[#5400] PS-9328: Merge 8.4.2 - Revert fix for PS-9125 Fix gtid_next formatting in Gtid_specification::automatic_to_string()

Reverting Percona Server version of the fix for PS-9125 as it became
unnecessary after Upstream's fix for bug#36308318 "GTID_NEXT accepts
Invalid value and also select shows wrong value".

For details see:
https://github.com/mysql/mysql-server/commit/a8c7f9bc16e16cb8095249ccf01a7e5641b4aa87
https://github.com/mysql/mysql-server/commit/2bb7af153b0e0603f939240be4d0cad01c89bd89

===================================================================================

[#5383] PS-9314 fix: Signal 11 when using JSON_TABLE

https://perconadev.atlassian.net/browse/PS-9314

As part of the 8.0.22 merge we added our fix (commit e29ddfe) for
Oracle's Bug #101401
"ISNULL continously returns the same value for LOAD_FILE"
(https://bugs.mysql.com/bug.php?id=101401)
However, when Oracle fixed the same issue in 8.0.23,
Bug #32096341
"ISNULL continuously returns the same value for LOAD_FILE"
(commit mysql/mysql-server@de4b3f7), ou fix never got reverted,
which introduced this regression.

Fixed by reverting our patch.

Extended 'main.func_str' MTR test case with additional checks for this
particular regression.

==========================================

Implemented PS-9389 (Merge MySQL 9.0.1) - conflicts solved (mysql-test)

==========================================

MTR fixtures: align with merge-9.0.1 reference

Final-parity reconciliation of mysql-test/ with dc2c257e3e3e (merge-9.0.1).

- Move innodb.percona_alter_debug and innodb.percona_create_table_8k to the
  percona_innodb suite as alter_debug and create_table_8k (rename only,
  content unchanged), matching the reference layout.
- main.func_str: the JSON_TABLE argument-type check expects
  ER_WRONG_ARGUMENTS ("Incorrect arguments to JSON_TABLE") as in the
  reference, instead of ER_INVALID_TYPE_FOR_JSON.

==========================================

[#5489] PS-9504: Replace `MY_NODISCARD` with `[[nodiscard]]`

We require at least gcc 7.1 or clang 5 for compilation which both support `[[nodiscard]]`.
`MY_NODISCARD` is no longer needed.

==========================================

[#5807] PS-10424: Fix `temporal-t.cc` compilation issue on macOS

Fix the following issue:
```
/Users/runner/work/1/s/unittest/gunit/temporal-t.cc:40:14: error: no matching constructor for initialization of 'MYSQL_TIME'
  MYSQL_TIME mytime(2023, 1, 30, 12, 0, 0, 0, false, MYSQL_TIMESTAMP_DATETIME,
             ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/1/s/include/mysql_time.h:82:16: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 10 were provided
typedef struct MYSQL_TIME {
               ^
/Users/runner/work/1/s/include/mysql_time.h:82:16: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 10 were provided
/Users/runner/work/1/s/include/mysql_time.h:82:16: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 10 were provided
1 error generated.
```

==========================================

PS-10979: Fix log_timestamp-t failure on hosts without CET zoneinfo

LogTimestampTest.iso8601 failed in Jenkins (RelWithDebInfo/ubuntu:resolute/
aarch64):

    Expected: "1970-01-01T01:00:00.000001+01:00"
    Which is: "1970-01-01T00:00:00.000001-00:00"
    Expected: "2011-07-07T02:00:00.000000+02:00"
    Which is: "2011-07-07T00:00:00.000000-00:00"

The test sets TZ=CET and expects the system-time ISO 8601 timestamp to carry a
+01:00 (winter) / +02:00 (summer) offset. The bare name "CET" relies on the
system timezone database (/usr/share/zoneinfo/CET). On minimal build/CI
containers that file is not installed, so glibc parses "CET" as a POSIX zone
with no offset rule, i.e. UTC. localtime_r() then returns tm_gmtoff == 0, the
time is not shifted and the offset is formatted as "-00:00" (the sign defaults
to '-' for a zero offset) - exactly the observed output.

Replace the bare "CET" with a fully-specified POSIX TZ string,
"CET-1CEST,M3.5.0,M10.5.0/3" (CET in winter, CEST in summer using the EU DST
rule). glibc evaluates this without consulting the timezone database, so the
expected +01:00 / +02:00 offsets are produced regardless of which zoneinfo
files the host provides. This mirrors what the Windows branch of the test
already does (it uses a POSIX-style string rather than a bare zone name).

Verified: the test passes both with the system tz database present and with it
made unavailable (TZDIR pointing at an empty directory, which reproduces the
Jenkins failure with the previous code).