[#4808] PS-8258 feature: Make Percona Server buildable on MacOS with RocksDB enabled
https://jira.percona.com/browse/PS-8258

In the top-level 'CMakeList.txt' file we now include 'extra/libkmip'
subdirectory only when 'KMIP' keying component is configured to be built.

RocksDB Storage Engine 'CMakeLists.txt' file now detects MacOS ('Darwin')
platform and adds 'OS_MACOSX' preprocessor definition.

'rt' system library no longer added to 'ha_rocksdb.so' as a dependency
on MacOS.

'rdb_buff.h' header from the RocksDB Storage Engine code extended with
a set of macros for emulating big-endian / little-endian
byte-manipulation functions for MacOS.

Some RocksDB system variables declared with 'MYSQL_SYSVAR_ENUM' were
using global variables of type 'uint64_t'. This was incompatible with
the macro definition as it expected variables of type 'ulong'. On Linux
platform it was not a problem as 'uint64_t' was defined as 'unsigned long'
there. However, on MacOS 'uint64_t' is defined as 'unsigned long long'.
Fixed by changing the type of underlying variables from 'uint64_t' to
'ulong'.

The family of 'MYSQL_SYSVAR_XXX' macros extended with
'MYSQL_SYSVAR_UINT64_T' that is supposed to be used for 'uint64_t'
variables. Because of the same reasons ('uint64_t' being defined
differently on Linux and MacOS) we needed this new macro to be able
bind system variables directly to RocksDB library variables that have
'uint64_t' type (the type of which we cannot change as this is RocksDB
submodule code).

A number of 'xxxprintf()' calls in the RocksDB Storage Engine code were
incorrectly using '%lu' format specifier for 'uint64_t' types. Again,
this was not a problem on Linux as 'uint64_t' was defined as
'unsigned long' there. For compatibility with MacOS, fixed by using
proper 'PRIu64' format specifier instead.

Fixed problem with passing an empty string to the 'std::regexp'
constructor that used to work on Linux but is not allowed by the
standard.
==========================================
[myrocks] [g7][#4808] PS-8258 feature: Make Percona Server buildable on MacOS with RocksDB

Original title:
[myrocks] [g7][#4808] PS-8258 feature: Make Percona Server buildable on MacOS with RocksDB enabled

https://jira.percona.com/browse/PS-8258

In the top-level 'CMakeList.txt' file we now include 'extra/libkmip'
subdirectory only when 'KMIP' keying component is configured to be built.

RocksDB Storage Engine 'CMakeLists.txt' file now detects MacOS ('Darwin')
platform and adds 'OS_MACOSX' preprocessor definition.

'rt' system library no longer added to 'ha_rocksdb.so' as a dependency
on MacOS.

'rdb_buff.h' header from the RocksDB Storage Engine code extended with
a set of macros for emulating big-endian / little-endian
byte-manipulation functions for MacOS.

Some RocksDB system variables declared with 'MYSQL_SYSVAR_ENUM' were
using global variables of type 'uint64_t'. This was incompatible with
the macro definition as it expected variables of type 'ulong'. On Linux
platform it was not a problem as 'uint64_t' was defined as 'unsigned long'
there. However, on MacOS 'uint64_t' is defined as 'unsigned long long'.
Fixed by changing the type of underlying variables from 'uint64_t' to
'ulong'.

The family of 'MYSQL_SYSVAR_XXX' macros extended with
'MYSQL_SYSVAR_UINT64_T' that is supposed to be used for 'uint64_t'
variables. Because of the same reasons ('uint64_t' being defined
differently on Linux and MacOS) we needed this new macro to be able
bind system variables directly to RocksDB library variables that have
'uint64_t' type (the type of which we cannot change as this is RocksDB
submodule code).

A number of 'xxxprintf()' calls in the RocksDB Storage Engine code were
incorrectly using '%lu' format specifier for 'uint64_t' types. Again,
this was not a problem on Linux as 'uint64_t' was defined as
'unsigned long' there. For compatibility with MacOS, fixed by using
proper 'PRIu64' format specifier instead.

Fixed problem with passing an empty string to the 'std::regexp'
constructor that used to work on Linux but is not allowed by the
standard.

Absorbed into this commit: include/mysql/plugin.h
==========================================

==========================================

[#5031] Explicitly specify std::max template type to use (#1187)

Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/c7a6020765b91dc504d4ed24fb3302d2f9250bed
PS-8494: Merge percona-202205 (https://jira.percona.com/browse/PS-8494)

Summary:
On macOS, one argument resolves to long, whereas the other resolves to long
long, leaving the compiler unable to deduce the template argument type. This is
not seen on Linux builds due to macOS std::int64_t definition differing from
that on Linux.

The build error is
```
/Users/laurynas/vilniusdb/fb-macos-port-draft/storage/rocksdb/properties_collector.cc:512:16: error: no matching function for call to 'max'
    num_keys = std::max(1L, static_cast<int64_t>(num_keys * adjustment_factor));
               ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:39:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long' vs. 'long long')
max(const _Tp& __a, const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:50:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:59:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__algorithm/max.h:30:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
```

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1187

Reviewed By: luqun

Differential Revision: D35550672

Pulled By: hermanlee

fbshipit-source-id: 808ae389bd12f670fb2ce469cfeb6ff7396f2c2d

==========================================

[final-parity] Reconcile remaining files with merge-8.0.33

Align all paths outside mysql-test/ with the reference
06765be444c1 (merge-8.0.33), which leaves a null tree diff. The
differences come from the reference merge-conflict resolutions, from
replay conflict resolutions onto MySQL 8.0.33, and from the TokuDB
submodule pointers the input branch never carried.

Files (55):
  M azure-pipelines.yml
  M client/mysqlbinlog.cc
  M components/mysqlbackup/backup_page_tracker.h
  M extra/robin-hood-hashing/robin_hood.h
  M include/m_string.h
  M include/my_alloc.h
  M include/mysql/components/services/page_track_service.h
  M libbinlogevents/include/debug_vars.h
  M man/mysqldumpslow.1
  M plugin/binlog_utils_udf/CMakeLists.txt
  M plugin/keyring_vault/tests/mtr/rpl_key_rotation.test
  M plugin/tokudb-backup-plugin/CMakeLists.txt
  A plugin/tokudb-backup-plugin/Percona-TokuBackup
  M router/src/routing/tests/CMakeLists.txt
  M router/tests/helpers/shared_server.cc
  M router/tests/helpers/shared_server.h
  M router/tests/integration/test_routing_reuse.cc
  M sql-common/sql_string.cc
  M sql/CMakeLists.txt
  M sql/binlog.cc
  M sql/binlog.h
  M sql/log_event.cc
  M sql/log_event.h
  M sql/memory/unique_ptr.h
  M sql/sql_class.cc
  M sql/sql_lex.cc
  M sql/sql_lex.h
  M sql/sql_parse.cc
  M sql/sql_prepare.cc
  M sql/sql_resolver.cc
  M storage/heap/hp_record.cc
  M storage/innobase/CMakeLists.txt
  M storage/innobase/buf/buf0dblwr.cc
  M storage/innobase/handler/i_s.cc
  M storage/innobase/include/btr0btr.h
  M storage/innobase/include/fil0fil.h
  M storage/innobase/include/os0file.h
  M storage/innobase/include/srv0srv.h
  M storage/innobase/include/trx0trx.h
  M storage/innobase/include/univ.i
  M storage/innobase/include/ut0new.h
  M storage/innobase/os/os0file.cc
  M storage/innobase/os/os0thread.cc
  M storage/innobase/row/row0log.cc
  M storage/innobase/row/row0sel.cc
  M storage/innobase/srv/srv0srv.cc
  M storage/innobase/trx/trx0trx.cc
  M storage/innobase/trx/trx0undo.cc
  M storage/ndb/CMakeLists.txt
  M storage/perfschema/terminology_use_previous.cc
  M storage/rocksdb/CMakeLists.txt
  A storage/tokudb/PerconaFT
  M unittest/gunit/mock_create_field.h
  M unittest/gunit/optimizer_test.h
  M unittest/gunit/strings_utf8-t.cc

=====================================================

PS-11625 Include <pthread.h> in MyRocks ib_ut0counter.h

https://perconadev.atlassian.net/browse/PS-11625

With the macOS legs on macOS-15, the scheduled 9.7 build gets as far as
Compile, and macOS 15 RelWithDebInfo then fails in ha_rocksdb.cc:

  storage/rocksdb/ib_ut0counter.h:90:45: error: use of undeclared
  identifier 'pthread_self'

get_curr_thread_id() expands to pthread_self(), but the header never
includes <pthread.h> and relied on getting it through other headers.
9.7 builds with CMAKE_CXX_STANDARD 23, and in C++23 mode libc++ no
longer pulls in <pthread.h> through the standard library headers. 8.4,
also on Apple clang 17 with the same image but built as C++20, compiles
the same header fine.

Include <pthread.h> next to the macro that uses it.