[#1378] Fix rocksdb.rocksdb_checksums inconsistency
Upstream commit ID: 5ed777647d244ad1bc7bd99eeea4915c6800a894

Summary:

Force the rocksdb.rocksdb_checksums test to flush the memtable and
generate consistent stats for the explain select statement.

Squash with D4213741
Reviewed By: yoshinorim
Differential Revision: D4279339

fbshipit-source-id: 3525f29

==========================================

[#1507] MYR-64 : 5.7 mtr - rocksdb.rocksdb_checksums fails MYR-59 : 5.7 mtr - re-record tes

Original title:
[#1507] MYR-64 : 5.7 mtr - rocksdb.rocksdb_checksums fails MYR-59 : 5.7 mtr - re-record tests for different EXPLAIN format - Test fails due to slightly different timestamp formatting between 5.6 and 5.7   and use of grep with explicit pattern. - Test also needed re-recording of EXPLAIN differences due to being masked by   failure. - Test used grep explicitly against mysqld.err file, converted to using   explicit log for this test and search_pattern.inc - Due to MyRocks perf issue on drop table with toumbstones, --repeat runs   on same server take forever. Changed to using specific database and dropping   on test completion. - Removed deprecated idioms.

==========================================

MYR-59 : 5.7 mtr - re-record tests for different EXPLAIN format

- Test fails due to slightly different timestamp formatting between 5.6 and 5.7
  and use of grep with explicit pattern.

- Test also needed re-recording of EXPLAIN differences due to being masked by
  failure.

- Test used grep explicitly against mysqld.err file, converted to using
  explicit log for this test and search_pattern.inc

- Due to MyRocks perf issue on drop table with toumbstones, --repeat runs
  on same server take forever. Changed to using specific database and dropping
  on test completion.

- Removed deprecated idioms.

==========================================

[#1347] update rocksdb submodule to include fix for rocksdb data inconsistency

Upstream commit ID: 5541f884cd83fbd01e222ad76816bb13df930620

Summary:
update rocksdb submodule to include fix for rocksdb data inconsistency here
https://github.com/facebook/rocksdb/commit/1168cb810a3b59c1245c870bc4ebece6d3f6d3bd

Test Plan: ran rocksdb suite, ensure all passes

Reviewers: gunnarku, vasilep, yoshinorim

Reviewed By: yoshinorim

Subscribers: webscalesql-eng

Differential Revision: https://reviews.facebook.net/D65487

[#1368] Fix the rocksdb.type_decimal test.

Upstream commit ID: 4f87819dca970c330c93a2316f3cc4fe0259219f

Summary:
Many of the other rocksdb.type_* tests specify the rocksdb_debug_optimizer_n_rows to avoid issues with the optimizer getting different results depending on how the test is run.  This test needed this flag set.
Closes https://github.com/facebook/mysql-5.6/pull/392

Reviewed By: gunnarku

Differential Revision: D4125668

Pulled By: jkedgar

fbshipit-source-id: e418f1b

==========================================

[#1390] rename rocksdb_disable_2pc to rocksdb_enable_2pc, default true

Upstream commit ID: 8dcea967fd948cf7d5baf6343bc4a15ffccecb0c

Summary:
This diff renames the flag rocksdb_disable_2pc to rocksdb_enable_2pc. The default for this value remains true, enabling 2pc by default.
Closes https://github.com/facebook/mysql-5.6/pull/471

Reviewed By: gunnarku

Differential Revision: D4321849

Pulled By: reidHoruff

fbshipit-source-id: 1b32ede

==========================================

[#1390] rename all rocksdb_disable_2pc to rocksdb_enable_2pc

Upstream commit ID: 54e915f43370bd048bc230cb30f6be0cd2e71d2f

Summary:
I missed the vars in 2pc_group_commit test. This renames rocksdb_disable_2pc to rocksdb_enable_2pc.

Squash with: D4321849

Reviewed By: anirbanr-fb

Differential Revision: D4432114

fbshipit-source-id: 6403c12

==========================================

[#1390] Updating the RocksDB submodule

Upstream commit ID: 922933bf0a0e1b24a1bdf652a9ff55dc931d392d

Summary:
Updated to the commit before 5.1.fb branch
bc5d7b70299b763127f3714055a63ebe7e04ad47

Reviewed By: yoshinorim

Differential Revision: D4442962

fbshipit-source-id: 7df16cd

==========================================

[#1390] Fix the build break caused by deprecated declarations from latest version of RocksD

Original title:
[#1390] Fix the build break caused by deprecated declarations from latest version of RocksDB

Upstream commit ID: 25b3da3637155f7ee882846e631ca81cde8ba8d2

Summary:
Currently the `{ latest MyRocks + latest RocksDB }` builds fails because `GetApproximateSizes` is marked as `ROCKSDB_DEPRECATED_FUNC`. This causes build errors like:

```
error: ‘virtual void rocksdb::DB::GetApproximateSizes(rocksdb::ColumnFamilyHandle*,
const rocksdb::Range*, int, uint64_t*, bool)’ is deprecated (declared at
.../rocksdb/include/rocksdb/db.h:629) [-Werror=deprecated-declarations]
     &sz, true);
```

This is a quick fix to unblock the integration testing.

Reviewed By: lth, VitaliyLi

Differential Revision: D4458637

fbshipit-source-id: 1b52d0c

==========================================

[#1396] MYR-50 : Fix compilation error introduced by upstream merge - Fixed compilation iss

Original title:
[#1396] MYR-50 : Fix compilation error introduced by upstream merge - Fixed compilation issue introduced by upstream merge of   a1badf05b5252ba9ba6b4808ec73cdc8cf9fbeef : Apply clang-format to everything   to unify MyRocks code   Committed to Percona Server 5.6 at 495057a3752beec08b209d30d1987dd62be23168 - Cherry pick merging commit dbdc0fa5e495d738cad1079d52bddca77e64a430 from ps-5.6-MYR-50

- Fixed compilation issue introduced by upstream merge of
  a1badf05b5252ba9ba6b4808ec73cdc8cf9fbeef : Apply clang-format to everything
  to unify MyRocks code
  Committed to Percona Server 5.6 at 495057a3752beec08b209d30d1987dd62be23168
- Cherry pick merging commit dbdc0fa5e495d738cad1079d52bddca77e64a430 from ps-5.6-MYR-50

==========================================

[#2432] Remove truncate error log from rocksdb.rocksdb_checksums test

Upstream commit ID : fb-mysql-5.6.35/f0cbe47e1b2dcdc8f8f9ca89f6b0fc8faab85e17
PS-4476 : Merge prod201801

Summary:
Restart the test using a new error log instead of truncating the old
error log. Also reduce the number of rows from 10000 to 4000 to speed up
the test.

Reviewed By: asandryh

Differential Revision: D7003203

fbshipit-source-id: 6b830ce

==========================================

[#4277] Fix rocksdb.rqg_runtime in write unprepared

Upstream commit ID : fb-mysql-5.6.35/4413d2f9506af0b77f52be2fb187fe75d9b1f666
PS-7606 : Merge fb-prod8-202010

Summary:
During online alter table, we occasional call transaction commit in order to refresh a snapshot. However, by calling commit, we're accidentally losing the name of the transaction.

When we lose the name of the transaction, this error occurs during transaction prepare:
```
[ERROR] [MY-000000] [Server] RocksDB: Failed to read/write in RocksDB, Status Code: 4, Status: Invalid argument: Cannot prepare a transaction that has not been named.
```

 We don't actually need to call commit in this case, as the intention was just to refresh the snapshot so that the newly bulk loaded keys become visible after `finalize_bulk_load`.

Reviewed By: yizhang82

Differential Revision: D26799937

fbshipit-source-id: b56d6b42915

==========================================

[#4362] Check for errors during inplace_populate_sk

Upstream commit ID : fb-mysql-5.6.35/c7c590acbcbfd60b1afbbc90c8162d8b5cadbc67
PS-7731 : Merge percona-202102

Summary: In `inplace_populate_sk`, `ha_index_init` can return an error if the query has been killed, and if that happens, it's not safe to continue with calling `index_first`/`index_next`. The fix is to check for errors and return early if needed.

Reviewed By: luqun

Differential Revision: D26960027 (https://github.com/facebook/mysql-5.6/commit/f12eea3370f5c147305afdf0727b355bcd2cf4ec)

fbshipit-source-id: eafc511dce4

==========================================

[final-parity] Reconcile storage/

Part of the PS-8581 8.0.32 merge conflict resolution (61fd625d5882),
which precedes the applied range:

  - storage/innobase/btr/btr0btr.cc: btr_search_enabled is atomic in
    8.0.32, so read it with .load() and drop the dict_sys->mutex assert.
  - storage/innobase/CMakeLists.txt: drop the clang-15
    -Wno-unused-but-set-variable suppression for fts/fts0pars.cc.
  - storage/innobase/dict/dict0load.cc and row/row0mysql.cc: blank-line
    only.
  - storage/rocksdb/rdb_i_s.cc and storage/tokudb/*: the
    TABLE_LIST -> Table_ref rename, Query_block::table_list ->
    m_table_list, and the bitmap_test_and_clear extern declaration.
  - storage/tokudb/CMakeLists.txt: the reference disables TokuDB with a
    RETURN() at the top of the file and restores the original
    WITH_TOKUDB guard below it.

==========================================

[#5576] Fixes to RocksDB MTR tests

Upstream commit ID: https://github.com/facebook/mysql-5.6/commit/27bc0f8db765
PS-9395: Merge percona-202401 (https://jira.percona.com/browse/PS-9395)

Summary: Wrapping RocksDB connection-creating tests in --source include/count_sessions.inc / wait_until_count_sessions.inc for stability.

Differential Revision: D51997562

fbshipit-source-id: 1b927ec1653579f932c96071e9d8821f8df75165