[components/keyring_vault] JEN-795 Failed connect to vault.public-ci.percona.com:8600
Original title:
[keyring_vault] JEN-795 Failed connect to vault.public-ci.percona.com:8600

===============================================

[#3013] JEN-795 Failed connect to vault.public-ci.percona.com:8600

vault.public-ci.percona was deemed to be unsecure and thus removed.
keyring_vault MTR test should use https://vault.percona.com, which is
maintained by IIT team. The tests were amended to use this new server.
The policy was changed to more strict one in comparision to
vault.public-ci.percona - the tests were also amended to cope with the
new policy.

Also new tests were added to test the separation of keyrings inside a
Vault server on directory level. For those tests only one new mount
point is created on the server and the separation is done by creating
separate directories inside the mount point - one directory per each
Percona server keyring_vault keyring.

The old tests are still checking the separation of keyrings with use of
separate mount points.

The not_repeat.inc was added to check whether the tests are not run with
--repeat > 1. This is because the tests are creating mount points at
the beginning of a run and delete when at the end of the run. When repeat is
used server will remember that it has already created master key and will
try to fetch the key. Unfortunately the key will be gone because the
mount point was deleted and re-created.

Changed the number of times the Master Key is rotated in
keyring_vault.table_encrypt_3.test and
keyring_vault.table_encrypt_3_directory to 100, so not to DoS the Vault Server.

Ported keyring_vault unittest to 8.0 - as they were not building,
enabled MERGE_UNITTESTS for keyring_vault as the linking of unittests
in 8.0 takes substantial amount of time.

Also clang-format-5.0 was applied.

(cherry picked from commit 78e4297ff14fa0f419fb29e8168399a24e9fca7c)

==========================================

[#3333] PS-5790: keyring_vault tests are failing on Jenkins

There is a bug in curl on Debian and it seems to not support http v2.
Because of that we should fall back to HTTP 1.1 in keyring_vault.
We should check when new fixes come around on Debian and re-check the
problem. Re-enable HTTP v2 in keyring_vault when the problem goes away
on Debian. There should not be any negative consequences security-wise
as all communication happens over TLS.

==========================================

[g5]PS-5363 (Merge MySQL 8.0.17): fixed/re-recorded a number of keyring_vault MTR test case

Original title:
[g5]PS-5363 (Merge MySQL 8.0.17): fixed/re-recorded a number of keyring_vault MTR test cases

The following MTR test cases from the 'keyring_vault' suite were
fixed/re-recorded due to a missing
"A message intended for a client cannot be sent there as no client-session is attached"
MTR warning suppression or new '/*!50503 ... */' version hint for
'SET character_set_client = utf8mb4' in 'mysqldump' output:
- 'keyring_vault.innodb_online_alter_encryption'
- 'keyring_vault.innodb_row_log_encryption'
- 'keyring_vault.table_encrypt_2'
- 'keyring_vault.table_encrypt_2_directory'
- 'keyring_vault.table_encrypt_2_keyring'
- 'keyring_vault.temp_table_encrypt_keyring_vault'.

==========================================

[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyrin

Original title:
[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyring_vault unit tests unconditionally)

https://jira.percona.com/browse/PS-4757

This check used to make sense only on Ubuntu Xenial, Fedora 28, Debian 8
and Debian 9 with buggy linker.
Fixing by backporting patches from 8.0 and extending them for Denian
distros.

Bug #29471723 "BROKEN BUILD FEDORA 28, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@304dfe8)
Bug #30594413 "BROKEN BUILD ON UBUNTU 16 32 BIT, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@2a45759)

==========================================

[final-parity] mysql-test

MTR reconciliation against merge-8.0.20:

- move the log_encrypt_7 and table_encrypt_6 bodies into
  mysql-test/include/*.inc and add the _mk / _rk wrappers;
- add the dblwr_file_count test and the log_encrypt_7 result files;
- drop the six -master.opt files merge-8.0.20 does not carry;
- extend innodb_parallel_doublewrite_path_basic.test with the
  deprecation-warning check;
- counter, .inc and .result drift across the suites.

Files folded in from that commit:
  mysql-test/include/table_encrypt_debug.inc
  mysql-test/include/table_encrypt_kill.inc
  mysql-test/suite/innodb/t/table_encrypt_3.test
  mysql-test/suite/innodb/t/table_encrypt_debug.test

==========================================

[#3888] PS-7133: keyring_vault unit tests fail on Jenkins.

Keyring Vault unittests started to fail when ctest started to run tests
in parallel. Each vault test suite created a mount point called <<server_uuid>> in
Vault server and created/removed keys in this mount point. When the
vault server test suites started to be executed in parallel all of
sudden they all started to use the same mount point, causing the tests
to fail. I have modified the test suites so each would create a
separate mount point called <<server_uuid_test_suite_name>>. Also the
configuration file generated to connect to Vault server is different per
each test suite.

==========================================

[myrocks] [g5][final-parity] Reconcile MTR fixtures with the reference

Test-fixture differences left after the replay, in three classes:

 * Result files that source commits re-applied in their mysql-8.0.26
   form, so they lost mysql-8.0.27 output changes: the fully qualified
   `test`.`tbl`.`col` names in EXPLAIN Note 1003 (group_by, view,
   bug74778, gis/bug77580, tokudb type_*/ctype_* and the rocksdb and
   *_rpl extra-column results), the perfschema setup_threads rows and
   the backup_locks / percona_heap_blob / pool_of_threads outputs.

 * The all_persisted_variables counters, which this replay carried
   forward commit by commit and which end one higher than the reference;
   set to the reference value of 497 in both the .test and the .result.

 * Fixtures belonging to reference-range commits with no source index,
   most visibly PS-8032 (innodb.log_inplace_alter_with_exclusiv_lock),
   the coredump test, valgrind.supp and the rpl/rpl_gtid additions.

Applied as a narrow patch restricted to mysql-test/** and the plugin
tests/mtr fixtures.

Split of 5b78780e5cdd6980db12fa8cea84b1ddaabe6e3c: 23 path(s) held back from group 5 (patch probe conflicted); the remaining 20 path(s) were promoted to group 5.

==========================================

[g8][#5044] PS-8723 merge: Merge MySQL 8.0.33 - Q2 2023 (ext::zlib fix) (#5044)

https://jira.percona.com/browse/PS-8723

A number of source files either directly or indirectly (via, say,
'sql_class.h') include 'my_checksum.h' header file which in turn
includes 'zlib.h' and has one of the inline functions referring to
'crc32_z()' function. The issue araises on old platforms (say,
CentOS7) that have pretty old system 'zlib' library in which
this function just does not exist. In other words, on such
platforms, we should always include 'zlib.h' from the 'bundled'
location.
However, because of the refactoring Oracle did in the CMake files
in the fix for the Bug #35057542
"Create INTERFACE libraries for bundled/system zlib/zstd/lz4"
(mysql/mysql-server@1f2b9d6), bundled 'zlib' include directory
is no longer set globally in 'MY_INCLUDE_SYSTEM_DIRECTORIES'.
Instead, individual targets are supposed to add 'ext::zlib'
to the list of dependencies via 'TARGET_LINK_LIBRARIES()'.

This commit adds missing 'ext::zlib' dependencies to
Percona-specific targets.