PS-4223 : 8.0 : Fix includes to be "sql/file.h" PS-4237 : 8.0 : 8.0 Need to explicitly incl
Original title:
PS-4223 : 8.0 : Fix includes to be "sql/file.h" PS-4237 : 8.0 : 8.0 Need to explicitly include sql/mysqld.h to pick up global system variables PS-4240 : 8.0 : 8.0 properly exports/exposes thd_binlog_format and thd_binlog_filter_ok via new header PS-4246 : 8.0 : 8.0 moved current_thd into own include file PS-4247 : 8.0 : 8.0 moved set_timespec_nsec from my_global.h to my_systime.h

PS-4237 : 8.0 : 8.0 Need to explicitly include sql/mysqld.h to pick up global system variables
PS-4240 : 8.0 : 8.0 properly exports/exposes thd_binlog_format and thd_binlog_filter_ok via new header
PS-4246 : 8.0 : 8.0 moved current_thd into own include file
PS-4247 : 8.0 : 8.0 moved set_timespec_nsec from my_global.h to my_systime.h

- Fixed various include directives to use new 8.0 pathing scheme,
  'include what you use', and proper code style format ordering.

- Removed local declarations and included correct headers for newly exposed
  functions.
==========================================
PS-4248 : 8.0 : 8.0 changes PSI_FLAG_GLOBAL to PSI_FLAG_SINGLETON

- Changed flag
==========================================
PS-4554 : 8.0 : 8.0 fixes gcc 8 warnings by providing init-defaults for complex types

- Removed now unneeded brace enclosed initializer for structs and replaced with
  constructor use where needed.
==========================================
[#2623] PS-4961 : Fix MyRocks compilation errors for Ubuntu 18.10 gcc 8.2.0

- Fixed error storage/rocksdb/ha_rocksdb.cc:561:70: error: type qualifiers
  ignored on cast result type [-Werror=ignored-qualifiers]

- Fixed error storage/rocksdb/rdb_datadic.cc:1108:78: error: type qualifiers
  ignored on cast result type [-Werror=ignored-qualifiers]

- Fixed error storage/rocksdb/rdb_threads.cc:29:71: error: type qualifiers
  ignored on cast result type [-Werror=ignored-qualifiers]

- Fixed error storage/rocksdb/rdb_datadic.cc:124:44: error:
  ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type
  ‘class myrocks::Rdb_field_packing’ with no trivial copy-assignment
  [-Werror=class-memaccess]

(cherry picked from commit 58363baefba0dd7f7c0e32d702a9f089a47d93a3)