[statement_set] This is implementation of this https://blueprints.launchpad.net/percona-ser
Original title:
[statement_set] This is implementation of this https://blueprints.launchpad.net/percona-server/+spec/per-qu

Original title:
This is implementation of this https://blueprints.launchpad.net/percona-server/+spec/per-query-variables-statement blueprint.

https://blueprints.launchpad.net/percona-server/+spec/per-query-variables-statement
blueprint.

Per query variable settings allow to set variable values only for the certain
query after execution of which the previous values are restored.

The original implementation can be found here: lp:~jlukas79/+junk/mysql-server

==========================================

[#335] Fix bug 1534874 (Assertion `(old_mh->m_key == key) || (old_mh->m_key == 0)' failed i

Original title:
[#335] Fix bug 1534874 (Assertion `(old_mh->m_key == key) || (old_mh->m_key == 0)' failed in mysys/my_malloc.c:80)

The assert shows that a memory block was allocated with one PFS memory
key (key_memory_per_query_vars), and later reallocated with a
different one (key_memory_THD_variables). The fix is to remove the
key_memory_per_query_vars key completely, as its memory blocks are
interchangeable with key_memory_THD_variables ones, thus it's
incorrect to have a separate memory key.

No testcase as it requires a SET STATEMENT FOR, then expanding global
variables list significantly, then a session variable query.
Expanding global variable list would require e.g. installing more than
one plugin (one plugin, such as Example SE is not sufficient for
reliable reproduction). And installing more than plugin is not
straightforward in MySQL Test Framework.
==========================================
[set_statement] Fix SET STATEMENT ... FOR <statement> crashes: 1) if <statement> needs to c

Original title:
[set_statement] Fix SET STATEMENT ... FOR <statement> crashes: 1) if <statement> needs to commit implicitly

Original title:
Fix SET STATEMENT ... FOR <statement> crashes: 1) if <statement> needs to commit implicitly and fails (bug 1418049); 2) if <statement> is RW in a RO transaction (bug 1387951); 3) if <statement> is needs to reopen a temp table and fails (bug 1412423).

1) if <statement> needs to commit implicitly and fails (bug 1418049);
2) if <statement> is RW in a RO transaction (bug 1387951);
3) if <statement> is needs to reopen a temp table and fails (bug 1412423).

All three bugs are related and caused by mysql_execute_command jumping
over to an error exit (one goto per each bug) and thus skipping
per_query_variables_backup variable initialization. But the cleanup of
restoring thd->variables from the uninitialzied variable still
happened. Fixed trivially.

This bug was also indicated by a compilation warning:

07:37:58 /home/jenkins/workspace/percona-server-5.6-debian-binary-32/label_exp/debian6-32/percona-server-5.6-5.6.22-71.0/sql/sql_parse.cc: In function 'int mysql_execute_command(THD*)':
07:37:58
/home/jenkins/workspace/percona-server-5.6-debian-binary-32/label_exp/debian6-32/percona-server-5.6-5.6.22-71.0/sql/sql_parse.cc:2609:
error: 'per_query_variables_backup' may be used uninitialized in this
function

fixing which is part of bug 1408232.

Added testcases.