[cpp] Fix gcc/clang compilation issues
[#2335] PS-3950: gcc-8 compilation warnings

1. Add gcc-8 to Travis config file
2. Fix the following gcc-8 warnings:
- cast between incompatible function types [-Werror=cast-function-type]
- clearing an object with no trivial copy-assignment [-Werror=class-memaccess]
- directive output may be truncated [-Werror=format-truncation=]
- type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
- catching polymorphic type 'class std::exception' by value [-Werror=catch-value=]

(cherry picked from commit 31b49ba6b4123dfab049357fc9a18d422dad741c)

===============================================================

[#2147] PS-3814: Fixing clang warnings after the upstream merge

* Removed unnecessary parentheses around a comparison
* Removed an unused global variable

===============================================================

[#2265] PS-3925: Use strncmp instead of memcmp in log_in_use

(cherry picked from commit 2c950c3ca2bf890549825417c10dd3065b78befc)
(cherry picked from commit 2fb17005e0d4b5d3c3c53d817e2be1c899a94e59)

PS-8581: Merge MySQL 8.0.32 - Fix gcc-7 and clang-8 compilation issues

===============================================================

[#4958] PS-8546: Eliminated dead code discovered with clang-15 compiler

===============================================================

[#2075] lp-1738171: Build error on FreeBSD with 5.6.38-83.0

Added <inttypes.h> include in plugin.h. FreeBSD maintainer suggested to include
<my_global.h> instead of <inttypes.h>. This increases code coherence.

(cherry picked from commit cf8bfa4ef1fcd90596cdcfda1146231cd2e8a124)

include/mysql/plugin.h: MYSQL_SYSVAR_UINT64_T folded from [#4808] PS-8258
"Make Percona Server buildable on MacOS with RocksDB enabled".

==========================================

[#5221] Implemented PS-8979 (Merge MySQL 8.2.0) (conflicts solved: code)

https://jira.percona.com/browse/PS-8979

Absorbed into this commit: storage/innobase/fts/fts0pars.cc

==========================================

sql/binlog/services/iterator/file_storage.cc: take the cursor-update
status with std::get<0>() instead of a structured binding whose unused
second element (event_size) trips unused-variable warnings with older
gcc; same form as the reference.

==========================================

[#5387] PS-9218: Merge MySQL 8.4.0 (fix gcc-14 build)

https://perconadev.atlassian.net/browse/PS-9218

==========================================

Revert "[compilation] PS-8581: Merge MySQL 8.0.32 - Fix gcc-7 and clang-8 compilation issue

Original title:
Revert "[compilation] PS-8581: Merge MySQL 8.0.32 - Fix gcc-7 and clang-8 compilation issues"

This reverts commit 24619f52422eb5528b67003654f5903f017854d7.

==========================================

Implemented PS-9389 (Merge MySQL 9.0.1) - conflicts solved (the rest)

==========================================

[#5513] [compilation] PS-9542: Fix clang-19 compilation issues

Fix 2 types of warnings:
1.
```
/data/mysql-server/percona-8.4/libs/mysql/serialization/serializer_default_impl.hpp:476:57: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  476 |     auto size_id_type = Archive_concrete_type::template get_size(
```
2.
```
/data/mysql-server/percona-8.4/router/src/metadata_cache/src/cluster_metadata_ar.h:77:43: error: empty paragraph passed to '@throws' command [-Werror,-Wdocumentation]
   77 |    * @throws metadata_cache::metadata_error
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
   78 |    */
```

==========================================

[other] PS-9598: Code refresh for 9.2.0-1 (conflicts solved)

==========================================

[cpp] Fix gcc-16 -Wunused-but-set-variable warnings

Moved here from "[upstream-squash] Restore bitmap locking; fix replication
checks and compiler warnings" so that the commits before it build with
g++-16 in maintainer mode: drop the unused loop counters in
do_sj_dups_weedout(), get_partition_set(), construct_options(),
PROFILING::fill_statistics_info(),
Query_block::transform_table_subquery_to_join_with_derived(),
TABLE::fill_item_list(), alter_templ_needs_rebuild(), rtree_delete_req() and
sp_make_key(), and pass -Wno-unused-but-set-variable to the bison-generated
sql_yacc.cc / sql_hints.yy.cc for GCC 16 as well as for Clang > 14.

Also silence the GCC 16 false-positive -Wmaybe-uninitialized in the
EchoSession / Session constructors of the NDB testSecureSocket and
testTlsKeyManager unit tests; moved here from
"[storage/ndb] Fix compiler warnings, printf annotation and daemon FILE leak".