[parallel_doublewrite] Implement parallel doublewrite
Original title:
[#377] Implement parallel doublewrite

Blueprint:
https://blueprints.launchpad.net/percona-server/+spec/parallel-doublewrite

New data structure for a single doublewrite partition: struct
parallel_dlbwr_shard_t, and a new structure for the whole doublewrite:
struct parallel_dblwr_t.

Remove batch doublewrite fields from struct buf_dblwr_t: first_free,
b_reserved, b_event, and batch_running.

New methods to support parallel doublewrite:
buf_parallel_dblwr_make_path, buf_parallel_dblwr_close,
buf_parallel_dblwr_delete, buf_parallel_dblwr_finish_recovery,
buf_parallel_dblwr_file_create, buf_parallel_dblwr_create,
buf_parallel_dblwr_destroy, buf_parallel_dblwr_partition,
buf_parallel_dblwr_shard_num.  New global variable
parallel_dblwr_buf.

Make buf_dblwr_init_or_load_pages to read any pages from the parallel
doublewrite file.

Delete the old one if existing and re-create the doublewrite buffer at
the end of buf_dblwr_process.

Make buf_dblwr_update to decrement atomically the remaining to process
page count for the batch flushing modes, and signal the doublewrite
partition event on the last one.

Make buf_dblwr_flush_buffered_writes take a doublewrite partition
index argument, remove the logic to sync with an already running
batch.

Make buf_dblwr_add_to_batch take a flush type argument in order to
find the correct doublewrite shard for the page being added. Remove
all logic to sync with an already running batch.

In buf_dblwr_update and buf_dblwr_flush_single_page, allow single page
flushes to take any slot in the legacy doublewrite buffer.  Simplify
the latter function.

Remove any synchronous flushing code so that no thread except from the
cleaner/LRU manager threads can do any kind of flushing by
itself. Instead, any other thread has to wait for the flusher threads
to do the required flushing. This affects buf_flush_sync_all_pools,
and log_preflush_pool_modified_pages.

Do not make log_checkpoint_at flush at the very end of server shutdown
when neither the page cleaner is running nor there can be dirty pages
in the buffer pool.

Destroy (and delete its file) the parallel doublewrite at the end of
logs_empty_and_mark_files_at_shutdown.

Delete the existing doublewrite buffer, if any, in
recv_recovery_from_checkpoint_start, if found that the instance does
not need crash recovery.

Create the doublewrite buffer in
innobase_start_or_create_for_mysql. Add an assert that any pages from
the old buffer have been used or it was impossible to use them due to
some condition (an error, high innodb_force_recovery value, etc).

Introduce new server variable innodb_parallel_doublewrite_path.

Register the parallel doublewrite file with Performance Schema.

Fix bug 1549301 / http://bugs.mysql.com/bug.php?id=80496
(buf_dblwr_init_or_load_pages now returns an error code, but caller
not updated) as the function in question now can return many more
errors related to the parallel doublewrite file I/O.

Add new possible flag, OS_FILE_O_SYNC, for os_file_create_simple_func.

Move suite/innodb/t/doublewrite.test to
include/doublewrite.inc. Create new innodb.doublewrite testcase that
simply includes that file and so has the same effect. Also create
innodb.doublewrite_multiple_pools that includes the same, but has two
buffer pool instances so that the tested data pages fall into
different doublewrite shards.

Create new testcase innodb.percona_doublewrite that tests the
doublewrite file handling, path setting, and error detection.

Create new testcase innodb.percona_doublewrite_single_page_flush that
tests the single page flush code path of the legacy doublewrite.

Update perfschema.show_sanity and create
sys_vars.innodb_percona_doublewrite_path testcase for the new
variable.

Make include/start_mysqld.inc and restart_mysqld.inc accept a one-shot
option $restart_hide_args, that would not print the actual server args
after the "# restart" string. This is done in order to test server
restart where the passed args should not be recorded in the output,
such as temp file paths.

Remove xb_doublewrite file in selected testcases manually as needed.
==========================================
[#491] Fix bug 1578139 (Parallel doublewrite memory not freed with innodb_fast_shutdown=2)

With a very fast InnoDB shutdown, buf_parallel_dblwr_destroy(), which
closes and deletes the doublewrite file and frees memory, is skipped.
In this configuration the file should not be deleted, thus fix by
renaming buf_parallel_dblwr_destroy() to buf_parallel_dblwr_free()
that unconditionally frees memory and, depending on the arg value,
closes and deletes the file. Call it in the common code path for all
innodb_fast_shutdown values.

==========================================

[#552] Fix bug 1586265 (Requesting flush burst to LSN_MAX is broken)

With parallel doublewrite, it is possible to call
buf_flush_request_force(LSN_MAX) to request flushing the whole of the
buffer pool, instead of performing query thread flushing as
previously. However, buf_flush_request_force does not process this
argument correctly as it adds lsn_avg_rate * 3 to its argument,
overflowing in the case of LSN_MAX. Fixed trivially.

==========================================

[#1096] Fix bug 1629879 (Server won't start with innodb_force_recovery=6 because parallel d

Original title:
[#1096] Fix bug 1629879 (Server won't start with innodb_force_recovery=6 because parallel doublewrite file exists)

With --innodb_force_recovery=6, the doublewrite buffer recovery is
skipped. But the instance may still write to the doublewrite buffer,
potentially overwriting the uncovered pages. With the parallel
doublewrite, the server already refuses to startup with
--innodb_force_recovery=6 if the doublewrite buffer file is present,
preventing the overwite of the uncovered pages. However the error
message is not intuitive, thus improve it.

==========================================

[parallel_doublewrite] Fix bug 1669414 (Failed to set O_DIRECT on xb_doublewrite when runni

Original title:
[parallel_doublewrite] Fix bug 1669414 (Failed to set O_DIRECT on xb_doublewrite when running MTR test cas

Original title:
[#1826] Fix bug 1669414 (Failed to set O_DIRECT on xb_doublewrite when running MTR test cases)

Fix handling of failure to set O_DIRECT on the parallel doublewrite
buffer by the following:
- downgrade diagnostics severity from warning to note by introducing
  an extra flag to os_file_setnocache and creating new logger helper
  class warn_or_info;
- introduce new flag parallel_dblwr_t::needs_flush. Initialize it in
  buf_parallel_dblwr_file_create according to innodb_flush_method
  value and whether setting O_DIRECT succeeded. Use it instead of
  innodb_flush_method value in buf_dblwr_flush_buffered_writes.
- fix an incorrect comment at os_file_create_func.

==========================================

PS-269 (Initial Percona Server 8.0.12 tree)

Trivially fix one of the multiple-buffer-pool-instance testcases.

==========================================

[#2747] PS-269: Fix percona_bug1380010, tablespace_option_encrypt, percona_doublewrite

1. Delete innodb.xtradb_read_view
2. Add `CHARACTER SET=latin1` to main.percona_bug1380010
3. Add missing `DROP TABLESPACE ts_valid2` to main.tablespace_option_encrypt
4. Add suppression to innodb.percona_doublewrite

==========================================

[#3230] Fix PS-5678 (Parallel doublewrite mustcrash server on I/O error)

buf_dblwr_flush_buffered_writes must crash server on an I/O error to
the doublewrite, as there is no way to continue flushing in such
event: proceeding with write to the data file defeats the purpose of
the doublewrite buffer. This was done in upstream legacy doublewrite,
however parallel doublewrite implementation changed the write call
from fil_io (which fails on error) to os_file_write (which returns
error to caller).

Fix by checking the return code of os_file_write and calling ib::fatal
on error.

==========================================

PS-5363 (Merge MySQL 8.0.17): fixed gcc-9 and clang-8 build issues

==========================================

PS-5363 (Merge MySQL 8.0.17): Fixed regression introduced in gcc-9 fix

==========================================

[#3499] PS-6052: gcc 9.2.1 reports new warnings

==========================================

PS-5363 (Merge MySQL 8.0.17): Code reformatting

Code reformatted with 'clang-format-8'.

==========================================

PS-5363 (Merge MySQL 8.0.17): Fixed problem with an assertion in srv_shutdown_all_bg_thread

Original title:
PS-5363 (Merge MySQL 8.0.17): Fixed problem with an assertion in srv_shutdown_all_bg_threads()

When started, thread created for 'srv_redo_log_follow_thread' was not stored
in the 'srv_threads.m_changed_page_tracker'.
In one of the code paths, 'srv_monitor_thread' when created was not stored in
the 'srv_threads.m_monitor'.
Similarly to the changes made in the fix for the Oracle Bug #29417503
"MYSQL COULD HANG DURING SHUTDOWN BECAUSE OF ZOMBIE IN MYSQL_TRX_LIST"
(commit mysql/mysql-server@cd6fab0)
(commit mysql/mysql-server@5f25a4a)
all reads of 'srv_shutdown_state' changed to 'srv_shutdown_state.load()'.

==========================================

PS-5363 (Merge MySQL 8.0.17): Fix innodb.percona_changed_page_bmp_crash test failure

Problem:
--------
With page tracking ON and innodb_fast_shutdown=2, server fails to
shutdown.

THis is because the redo log tracker thread doesn't exit when
innodb_fast_shutdown=2

Fix:
----
Wake up the redo log tracker thread on innodb_fast_shutdown=2 as well

==========================================

[#3817] PS-7032: fix gcc-10 compilation issues (8.0)

Fix gcc-10 compilation issues:
1.
```
In file included from /home/travis/build/percona/percona-server/include/my_time.h:37,
                 from /home/travis/build/percona/percona-server/sql/field.h:46,
                 from /home/travis/build/percona/percona-server/sql/table_column_iterator.h:28,
                 from /home/travis/build/percona/percona-server/sql/log_event.h:88,
                 from /home/travis/build/percona/percona-server/sql/binlog_reader.h:27,
                 from /home/travis/build/percona/percona-server/sql/rpl_applier_reader.h:28,
                 from /home/travis/build/percona/percona-server/sql/rpl_applier_reader.cc:23:
/home/travis/build/percona/percona-server/sql/rpl_applier_reader.cc: In member function ‘void Rpl_applier_reader::Stage_controller::enter_stage()’:
/home/travis/build/percona/percona-server/sql/rpl_applier_reader.cc:69:25: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
   69 |     DBUG_ASSERT(m_state = LOCKED);
      |                 ~~~~~~~~^~~~~~~~
/home/travis/build/percona/percona-server/sql/rpl_applier_reader.cc:69:5: note: in expansion of macro ‘DBUG_ASSERT’
   69 |     DBUG_ASSERT(m_state = LOCKED);
      |     ^~~~~~~~~~~
```
2.
```
/data/mysql-server/percona-8.0/storage/innobase/buf/buf0dblwr.cc: In function ‘dberr_t buf_parallel_dblwr_create()’:
/data/mysql-server/percona-8.0/storage/innobase/buf/buf0dblwr.cc:1499:71: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct parallel_dblwr_shard_t’ with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
 1499 |   memset(parallel_dblwr_buf.shard, 0, sizeof(parallel_dblwr_buf.shard));
      |                                                                       ^
In file included from /data/mysql-server/percona-8.0/storage/innobase/buf/buf0dblwr.cc:38:
/data/mysql-server/percona-8.0/storage/innobase/include/buf0dblwr.h:182:8: note: ‘struct parallel_dblwr_shard_t’ declared here
  182 | struct parallel_dblwr_shard_t {
      |        ^~~~~~~~~~~~~~~~~~~~~~
```
3.
```
/data/mysql-server/percona-8.0/sql/rpl_binlog_sender.cc: In member function 'void Binlog_sender::run()':
/data/mysql-server/percona-8.0/sql/rpl_binlog_sender.cc:362:42: error: '%s' directive output may be truncated writing up to 511 bytes into a region of size between 427 and 938 [-Werror=format-truncation=]
  362 |                "the last byte read from '%s' at %lld.",
      |                                          ^~
/data/mysql-server/percona-8.0/sql/rpl_binlog_sender.cc:360:16: note: using the range [-9223372036854775808, 9223372036854775807] for directive argument
  360 |                "%s; the first event '%s' at %lld, "
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  361 |                "the last event read from '%s' at %lld, "
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  362 |                "the last byte read from '%s' at %lld.",
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/c++/10/cstdio:42,
                 from /data/mysql-server/percona-8.0/libbinlogevents/include/binlog_event.h:42,
                 from /data/mysql-server/percona-8.0/sql/rpl_binlog_sender.h:30,
                 from /data/mysql-server/percona-8.0/sql/rpl_binlog_sender.cc:23:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:35: note: '__builtin___snprintf_chk' output 94 or more bytes (assuming 1116) into a destination of size 1024
   64 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   65 |        __bos (__s), __fmt, __va_arg_pack ());
```
4.
```
In file included from /data/mysql-server/percona-8.0/unittest/gunit/integer_digits-t.cc:25:
In function 'char* write_digits(T, int, char*) [with T = long unsigned int]',
    inlined from 'virtual void integer_digits_unittest::IntegerDigits_WriteDigits_Test::TestBody()' at /data/mysql-server/percona-8.0/unittest/gunit/integer_digits-t.cc:74:27:
/data/mysql-server/percona-8.0/include/integer_digits.h:152:12: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  152 |     *--pos = '0' + number % 10;
      |     ~~~~~~~^~~~~~~~~~~~~~~~~~~
/data/mysql-server/percona-8.0/unittest/gunit/integer_digits-t.cc: In member function 'virtual void integer_digits_unittest::IntegerDigits_WriteDigits_Test::TestBody()':
/data/mysql-server/percona-8.0/unittest/gunit/integer_digits-t.cc:73:8: note: at offset -1 to object 'buffer' with size 100 declared here
   73 |   char buffer[100];
```