[router] gcc/clang compilation + build fixes
PS-8581: Merge MySQL 8.0.32 - Fix "routertest_integration_routing_*" unit tests

==========================================

PS-8581: Merge MySQL 8.0.32 - ASan: fix "routertest_integration_routing_*" memory leaks

==========================================

[final-parity] router: sql_lexer also depends on GenError

ADD_DEPENDENCIES(sql_lexer GenServerSource GenError) - the generated
error headers are needed alongside sql_yacc.h.

This hunk has no in-range blame owner (no other commit in
mysql-8.0.32..HEAD touches router/src/routing/src/); it is placed with
the other PS-8581 merge router fixes.

Folded from the [final-parity] reconciliation of the PS-8581 8.0.32
merge conflict resolution (61fd625d5882).

==========================================

PS-8581: Merge MySQL 8.0.32 - Fix gcc-7 and clang-8 compilation issues (router)

router/src/harness/tests/linux_timestamping.cc: define is_type_complete_v
only under SO_TIMESTAMPING && !SO_TIMESTAMPING_NEW, the only case where the
fallback scm_timestamping check uses it.

Extracted from "[#2335] PS-3950: Fix gcc/clang compilation issues".

==========================================

[myrocks] [g7][#5078] PS-8820 [5.7]: Add gcc-13 and clang-16 to Azure Pipelines and fix gcc

Original title:
[myrocks] [g7][#5078] PS-8820 [5.7]: Add gcc-13 and clang-16 to Azure Pipelines and fix gcc-13 compilation issues

1. Add gcc-13 and clang-16 to Azure Pipelines
2. Update RocksDB submodule pointer

-------------------------------------------------------------------------------

[cmake] Bug #109325: Ubuntu 22.04 forces LTO compilation with gcc in RelWithDebInfo

Remove LTO flags from `dpkg-buildflags`.

Ubuntu 22.04 Jammy returns:
```
$ dpkg-buildflags --get CXXFLAGS
-g -O2 -ffile-prefix-map=/data/mysql-server=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
```

Ubuntu 20.04 returns:
```
$ dpkg-buildflags --get CXXFLAGS
-g -O2 -fdebug-prefix-map=/data/docker=. -fstack-protector-strong -Wformat -Werror=format-security
```

After this patch the result for Ubuntu 22.04 matches Ubuntu 20.04.

================================================================

[#5131] PS-8844: Merge MySQL 8.0.34 - Fix routertest_integration_routing_sharing_constrained_pools unit test

==========================================

[#5221] Implemented PS-8979 (Merge MySQL 8.2.0) (conflicts solved: code)

https://jira.percona.com/browse/PS-8979

Absorbed into this commit: router/src/routing/tests/CMakeLists.txt

==========================================

[#5221] PS-8979: Fix timeout in "routertest_integration_routing_sharing"

Increase timeout for "routertest_integration_routing_sharing" to 3000 seconds.

(cherry picked from commit fff26dd61a185fd82c351ba96b5d5fdd3005b050)

==========================================

[#5221] PS-8979: Merge MySQL 8.2.0 (unit tests fix)

https://jira.percona.com/browse/PS-8979

The router integration tests were failing due to incorrectly set
MYSQLD_BIN which was set to 'mysqld-debug' or 'mysqld' depending on
NDEBUG option state.
The binary name actually depends on DEBUG_EXTNAME value. Changed
MYSQLD_BIN to be set similarly.

Fixed freeaddrinfo() invocation on uninitialized pointer in NdbTCP test.

==========================================

[#5283] PS-9071: Merge MySQL 8.3.0 (fix test_routing_direct tests)

https://perconadev.atlassian.net/browse/PS-9071

Tests lack knowledge of some Percona and debug build specific system
variable names.
Updated known system variables lists for tests to be able to categorize
them properly.

==========================================

Revert "[compilation] PS-8581: Merge MySQL 8.0.32 - Fix gcc-7 and clang-8 compilation issue

Original title:
Revert "[compilation] PS-8581: Merge MySQL 8.0.32 - Fix gcc-7 and clang-8 compilation issues"

This reverts commit 24619f52422eb5528b67003654f5903f017854d7.

==========================================

Revert "[compilation] PS-8185 - Fix compilation of ROUTER on clang 7"

This reverts commit 2ffd182bd80569a23a3b20729530b8478148b41f.

==========================================

PS-9388: Fix "routertest_integration_routing*"

Fix the following issue:
```
273: /data/mysql-server/8.x/router/tests/helpers/process_manager.cc:732: Failure
273: Expected equality of these values:
273:   expected_exit_status
273:     Which is: Exit(0)
273:   result
273:     Which is: Exit(128)
273: Process 1325111 exited with Exit(128)
273: /data/mysql-server/8.x/router/tests/helpers/process_manager.cc:669: Failure
273: Failed
273: # Process: (pid=1325111)
273: /data/mysql-server/8.x-deb-gcc13-rocks/runtime_output_directory/mysqld --no-defaults --lc-messages-dir=/data/mysql-server/8.x-deb-gcc13-rocks/share --datadir=/tmp/mysqld-debug-0Pfsrx --plugin_dir=/data/mysql-server/8.x-deb-gcc13-rocks/plugin_output_directory --log-error=/tmp/mysqld-debug-0Pfsrx/mysqld-0.err --port=11010 --socket=/tmp/mysqld-debug-0Pfsrx/mysql.sock --mysqlx-port=11011 --mysqlx-socket=/tmp/mysqld-debug-0Pfsrx/mysqlx.sock --secure-file-priv=NULL --innodb_redo_log_capacity=8M --innodb_autoextend_increment=1 --innodb_buffer_pool_size=5M --innodb_use_native_aio=0 --gtid_mode=ON --enforce_gtid_consistency=ON --relay-log=relay-log
273:
273: ## Console output:
273:
273: /data/mysql-server/8.x-deb-gcc13-rocks/runtime_output_directory/mysqld could not be executed: No such file or directory (errno 2)
273:
273: ## Log content:
273:
273: <THIS ERROR COMES FROM TEST FRAMEWORK'S get_file_output(), IT IS NOT PART OF PROCESS OUTPUT: Could not open file '/tmp/mysqld-debug-0Pfsrx/mysqld-0.err' for reading: basic_ios::clear: iostream error>
273:
273: /data/mysql-server/8.x/router/tests/helpers/process_manager.cc:732: Failure
273: Expected equality of these values:
273:   expected_exit_status
273:     Which is: Exit(0)
273:   result
273:     Which is: Exit(128)
273: Process 1325111 exited with Exit(128)
```

==========================================

[router] PS-9542: Fix clang-19 compilation issues

Fix 2 types of warnings:
1.
```
/data/mysql-server/percona-8.4/libs/mysql/serialization/serializer_default_impl.hpp:476:57: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  476 |     auto size_id_type = Archive_concrete_type::template get_size(
```
2.
```
/data/mysql-server/percona-8.4/router/src/metadata_cache/src/cluster_metadata_ar.h:77:43: error: empty paragraph passed to '@throws' command [-Werror,-Wdocumentation]
   77 |    * @throws metadata_cache::metadata_error
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
   78 |    */
```

==========================================

[#5700] PS-10049 [9.x] merge: Code refresh for - PS 8.4.6-6 (gcc-12 RelWithDebInfo warning fix)

https://perconadev.atlassian.net/browse/PS-10049

Suppressed the following warning in the "router" tests code that appears
on gcc-12 in RelWithDebInfo build configuration.

In file included from /usr/include/c++/12/ios:40,
                 from /usr/include/c++/12/istream:38,
                 from /usr/include/c++/12/sstream:38,
                 from /home/yura/ws/percona-server-8.4/router/src/routing/tests/../src/basic_protocol_splicer.h:33,
                 from /home/yura/ws/percona-server-8.4/router/src/routing/tests/../src/processor.h:29,
                 from /home/yura/ws/percona-server-8.4/router/src/routing/tests/../src/classic_quit_sender.h:29,
                 from /home/yura/ws/percona-server-8.4/router/src/routing/tests/test_classic_quit_sender.cc:26:
In static member function ‘static constexpr std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)’,
    inlined from ‘static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:431:21,
    inlined from ‘static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:426:7,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.tcc:532:22,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:2179:19,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:2204:22,
    inlined from ‘std::string testing::internal::CanonicalizeForStdLibVersioning(std::string)’ at /home/yura/ws/percona-server-8.4/extra/googletest/googletest-1.14.0/googletest/include/gtest/internal/gtest-type-util.h:83:14:
/usr/include/c++/12/bits/char_traits.h:435:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  435 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

==========================================

[#5700] PS-10061: Code refresh for 9.4.0-1 (Fix routertest_integration_routing_direct, routertest_integration_routing_splitting)

==========================================

[#5700] PS-10061: Code refresh for 9.4.0-1 (Fix macOS build)

```
In file included from /Users/runner/work/1/s/router/src/mysql_rest_service/src/mrs/endpoint/content_file_endpoint.cc:26:
In file included from /Users/runner/work/1/s/router/src/mysql_rest_service/src/mrs/endpoint/content_file_endpoint.h:29:
In file included from /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/memory:884:
In file included from /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__memory/allocate_at_least.h:13:
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__memory/allocator_traits.h:304:9: error: no matching function for call to 'construct_at'
        _VSTD::construct_at(__p, _VSTD::forward<_Args>(__args)...);
        ^~~~~~~~~~~~~~~~~~~
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__config:897:17: note: expanded from macro '_VSTD'
                ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/vector:919:21: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<http::base::UriPathMatcher>>::construct<http::base::UriPathMatcher, const std::string &, bool, bool, void, void>' requested here
    __alloc_traits::construct(this->__alloc(), std::__to_address(__tx.__pos_),
                    ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/vector:1678:9: note: in instantiation of function template specialization 'std::vector<http::base::UriPathMatcher>::__construct_one_at_end<const std::string &, bool, bool>' requested here
        __construct_one_at_end(std::forward<_Args>(__args)...);
        ^
/Users/runner/work/1/s/router/src/mysql_rest_service/src/mrs/endpoint/handler/helper/url_paths.h:128:14: note: in instantiation of function template specialization 'std::vector<http::base::UriPathMatcher>::emplace_back<const std::string &, bool, bool>' requested here
      result.emplace_back(service_schema_path, false, false);
             ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__memory/construct_at.h:39:38: note: candidate template ignored: substitution failure [with _Tp = http::base::UriPathMatcher, _Args = <const std::string &, bool, bool>]: no matching constructor for initialization of 'http::base::UriPathMatcher'
_LIBCPP_HIDE_FROM_ABI constexpr _Tp* construct_at(_Tp* __location, _Args&&... __args) {
```

==========================================

PS-10166 [9.x]: Suppress `test_microbench.cc` compilation error with arm64

```
/usr/include/c++/13/bits/basic_string.h:266:17: error: ‘*(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)((char*)&<unnamed> + offsetof(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >,std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::<unnamed>.std::_Optional_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, false>::<unnamed>)).std::__cxx11::basic_string<char>::_M_string_length’ may be used uninitialized [-Werror=maybe-uninitialized]
  266 |             if (_M_string_length > _S_local_capacity)
      |                 ^~~~~~~~~~~~~~~~
/usr/include/c++/13/bits/new_allocator.h: In member function ‘stdx::expected<typename classic_protocol::Codec<T>::value_type, std::error_code> classic_protocol::impl::DecodeBufferAccumulator::step(size_t) [with T = classic_protocol::borrowable::message::client::Query<false>]’:
/usr/include/c++/13/bits/new_allocator.h:191:11: note: ‘<anonymous>’ declared here
  191 |         { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [router/src/mysql_protocol/tests/CMakeFiles/routertest_mysql_protocol_microbench.dir/build.make:76: router/src/mysql_protocol/tests/CMakeFiles/routertest_mysql_protocol_microbench.dir/test_microbench.cc.o] Error 1
```

==========================================

PS-10166 [9.x]: Stabilize `routertest_integration_routing_sharing_restart` unit test

==========================================

PS-10183 [9.x]: Make MySQL Rest Service compatible with Percona Server binary releases (fix 'router' suite failures in Jenkins).

MySQL Rest Service (MRS) is a part of MySQL Router which was introduced
as part of Upstream 9.3 release.

It did explicit compatibility check which allowed it to work only with
servers which @@version_comment started with "MySQL" (i.e. binary releases
from Oracle) or contained "Source distribution" as a substring. Naturally,
this made it incompatible with binary releases of Percona Server for MySQL.

As result all MTR tests in 'router' suite failed in our Jenkins (where
we test binary "release").

This commit fixes the problem by adjusting this compatibility check to
accept Percona Server binary releases.