[backup_locks] PS-4758: A sequence of LOCK TABLES FOR BACKUP and STOP SLAVE SQL_THREAD can
Original title:
[backup_locks] PS-4758: A sequence of LOCK TABLES FOR BACKUP and STOP SLAVE SQL_THREAD can cause r

===============================================

[#2832] PS-4758: A sequence of LOCK TABLES FOR BACKUP and STOP SLAVE SQL_THREAD can cause replication to be blocked and cannot be restarted normally

can cause replication to be blocked and cannot be restarted normally

When after LOCK TABLES FOR BACKUP / LOCK BINLOG FOR BACKUP slave SQL
thread is waiting for backup / binlog lock subsequent STOP SLAVE
SQL_THREAD causing deadlock. SQL thread is waiting for backup lock, STOP
SLAVE is waiting for SQL thread to complete current statement.

Fix is to throw an error when the thread which acquired the backup lock
is trying to stop slave.

==========================================

[backup_locks] PS-4758: post merge fix

===============================================

[#2846] PS-4758: post merge fix

8.0 version of the fix incorrectly determined whether the thread has
acquired LOCK INSTANCE FOR BACKUP lock. Instead it determined if the
lock has been acquired by any thread.

Fix is to use MDL_context::owns_equal_or_stronger_lock to check if
current thread owns the lock.

===============================================

[#3154] PS-5360 : Implement server side changes for XtraBackup MyRocks PS-5362 : Create new session variable rocksdb_create_temporary_checkpoint PS-5362 : Expose RocksDB WAL position through I_S.log_status PS-5563 : Create new session variable rocksdb_disable_file_deletions PS-5583 : Lock tables for backup blocks DML for RocksDB

PS-5362 : Create new session variable rocksdb_create_temporary_checkpoint
PS-5362 : Expose RocksDB WAL position through I_S.log_status
PS-5563 : Create new session variable rocksdb_disable_file_deletions
PS-5583 : Lock tables for backup blocks DML for RocksDB

- Temporarily forked RocksDB into percona/rocksdb and created temp branch
  (ps-5362) pointing to same commit that 8.0 currently points to
  (516c7df05dd267e4725e7dd061a6767de7aayyac0d).

- Cherry-picked Sergeis work onto new RocksDB branch (ps-5362) in new temp fork.

- Repointed Percona Server RocksDB git submodule commit pointer to point to new
  fork (percona/rocksdb) at same commit that was previously pointed to
  (516c7df05dd267e4725e7dd061a6767de7aayyac0d) +1 commit to Sergeis
  cherry-picked work (3f5c1236026233b34be64d597fe660d7e698f2f5).

- Added new session variable to MyRocks rocksdb_create_temporary_checkpoint
  which will create a temporary RocksDB 'checkpoint' or 'snapshot'.  If the
  session ends with an existingcheckpoint, or if the variable is reset to
  another value, the checkpoint will get removed.

- Added new session variable to MyRocks rocksdb_disable_file_deletions, which
  when set, will tell RocksDB to disable the deletion of old WAL and .sst files.
  If the session ends without re-enabling file deletion, file deletions will be
  explicitly re-enabled.

- Expose rocksdb WAL position in i_s.log_status table.

- Added tests to MyRocks for new options and behaviors.

- Added HTON_SUPPORTS_ONLINE_BACKUPS to MyRocks handlerton flags.

- Split main.backup_locks and rpl.rpl_backup_locks tests into common includes
  with engine and feature controlling options and updating to use modern
  semantics.  Implemented InnoDB and MyRocks tests based on these new common
  tests and recorded.

- Updated documentation to reflect MyRocks support/inclusion in LTFB.

==========================================

PS-5363 (Merge MySQL 8.0.17): Fix clone tests failing with Can't execute the given command

Original title:
PS-5363 (Merge MySQL 8.0.17): Fix clone tests failing with Can't execute the given command because you have active locked tables or an active transaction

The fix for PS-4758 (8.0) has multiple parts.
1. Handle LOCK TABLES FOR BACKUP;
2. Hanlde LOCK BINLOG FOR BACKUP;
3. Handle LOCK INSTANCE FOR BACKUP;

3 is reported as upstream bug https://bugs.mysql.com/bug.php?id=93649

And it is fixed by Oracle:
commit 7e75ca24a273bd2e1aaa662e6712025c4dd8e0ca
Author: Pedro Figueiredo <pedro.figueiredo@oracle.com>
Date:   Tue Apr 23 14:57:48 2019 +0100

    BUG#29386503 STOP SLAVE SQL_THREAD DEADLOCKS IF DONE WHILE HOLDING LOCK INSTANCE FOR BACKUP

Fix:
----
Our fix for 3 is un-necessary (duplicate and doesn't handle Clone). So
we revert fix for 3.

==========================================

[g6]PS-6866: Merge fb-prod201904 (8.0)

https://jira.percona.com/browse/PS-6866

==========================================

[g6][#3772] PS-6966: fix clang-10 compilation issues

1. Update PerconaFT submodule pointer to https://github.com/percona/PerconaFT/commit/ba5ca618e0a192c685afe38617c867ba81c93c66
2. Remove PerconaFT suppression for the `-Wno-address-of-packed-member` warning
3. Fix clang-10 issue:
```
/percona-5.6/storage/myisam/mi_rkey.c:189:5: error: misleading indentation; statement is not part of the previous 'else' [-Werror,-Wmisleading-indentation]
    info->set_rnext_same_key= TRUE;
```

===========================================================

[#3772] PS-6966: fix clang-10 compilation issues (mysql-8.0)