[keyring_vault] JEN-795 Failed connect to vault.public-ci.percona.com:8600
===============================================

[#3013] JEN-795 Failed connect to vault.public-ci.percona.com:8600

vault.public-ci.percona was deemed to be unsecure and thus removed.
keyring_vault MTR test should use https://vault.percona.com, which is
maintained by IIT team. The tests were amended to use this new server.
The policy was changed to more strict one in comparision to
vault.public-ci.percona - the tests were also amended to cope with the
new policy.

Also new tests were added to test the separation of keyrings inside a
Vault server on directory level. For those tests only one new mount
point is created on the server and the separation is done by creating
separate directories inside the mount point - one directory per each
Percona server keyring_vault keyring.

The old tests are still checking the separation of keyrings with use of
separate mount points.

The not_repeat.inc was added to check whether the tests are not run with
--repeat > 1. This is because the tests are creating mount points at
the beginning of a run and delete when at the end of the run. When repeat is
used server will remember that it has already created master key and will
try to fetch the key. Unfortunately the key will be gone because the
mount point was deleted and re-created.

Changed the number of times the Master Key is rotated in
keyring_vault.table_encrypt_3.test and
keyring_vault.table_encrypt_3_directory to 100, so not to DoS the Vault Server.

Ported keyring_vault unittest to 8.0 - as they were not building,
enabled MERGE_UNITTESTS for keyring_vault as the linking of unittests
in 8.0 takes substantial amount of time.

Also clang-format-5.0 was applied.

(cherry picked from commit 78e4297ff14fa0f419fb29e8168399a24e9fca7c)

==========================================

[#3333] PS-5790: keyring_vault tests are failing on Jenkins

There is a bug in curl on Debian and it seems to not support http v2.
Because of that we should fall back to HTTP 1.1 in keyring_vault.
We should check when new fixes come around on Debian and re-check the
problem. Re-enable HTTP v2 in keyring_vault when the problem goes away
on Debian. There should not be any negative consequences security-wise
as all communication happens over TLS.

==========================================

[g5]PS-5363 (Merge MySQL 8.0.17): fixed/re-recorded a number of keyring_vault MTR test case

Original title:
[g5]PS-5363 (Merge MySQL 8.0.17): fixed/re-recorded a number of keyring_vault MTR test cases

The following MTR test cases from the 'keyring_vault' suite were
fixed/re-recorded due to a missing
"A message intended for a client cannot be sent there as no client-session is attached"
MTR warning suppression or new '/*!50503 ... */' version hint for
'SET character_set_client = utf8mb4' in 'mysqldump' output:
- 'keyring_vault.innodb_online_alter_encryption'
- 'keyring_vault.innodb_row_log_encryption'
- 'keyring_vault.table_encrypt_2'
- 'keyring_vault.table_encrypt_2_directory'
- 'keyring_vault.table_encrypt_2_keyring'
- 'keyring_vault.temp_table_encrypt_keyring_vault'.

==========================================

[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyrin

Original title:
[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyring_vault unit tests unconditionally)

https://jira.percona.com/browse/PS-4757

This check used to make sense only on Ubuntu Xenial, Fedora 28, Debian 8
and Debian 9 with buggy linker.
Fixing by backporting patches from 8.0 and extending them for Denian
distros.

Bug #29471723 "BROKEN BUILD FEDORA 28, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@304dfe8)
Bug #30594413 "BROKEN BUILD ON UBUNTU 16 32 BIT, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@2a45759)

==========================================

[final-parity] mysql-test

MTR reconciliation against merge-8.0.20:

- move the log_encrypt_7 and table_encrypt_6 bodies into
  mysql-test/include/*.inc and add the _mk / _rk wrappers;
- add the dblwr_file_count test and the log_encrypt_7 result files;
- drop the six -master.opt files merge-8.0.20 does not carry;
- extend innodb_parallel_doublewrite_path_basic.test with the
  deprecation-warning check;
- counter, .inc and .result drift across the suites.

Files folded in from that commit:
  mysql-test/include/table_encrypt_debug.inc
  mysql-test/include/table_encrypt_kill.inc
  mysql-test/suite/innodb/t/table_encrypt_3.test
  mysql-test/suite/innodb/t/table_encrypt_debug.test

==========================================

[#3888] PS-7133: keyring_vault unit tests fail on Jenkins.

Keyring Vault unittests started to fail when ctest started to run tests
in parallel. Each vault test suite created a mount point called <<server_uuid>> in
Vault server and created/removed keys in this mount point. When the
vault server test suites started to be executed in parallel all of
sudden they all started to use the same mount point, causing the tests
to fail. I have modified the test suites so each would create a
separate mount point called <<server_uuid_test_suite_name>>. Also the
configuration file generated to connect to Vault server is different per
each test suite.