[components/keyring_vault] New plugin: keyring_vault
Original title:
[#1852] New plugin: keyring_vault

Blueprint:
https://blueprints.launchpad.net/percona-server/+spec/keyring-vault

Plugin for storing, removing and fetching keys from Hashicorp Vault.

MTR keyring tests were refactored so they could be used with different
keyring plugins, in this particular case with keyring_vault.

New unit tests test suite for keyring_vault were added.

Plugin requires CURL library in order to build.

==========================================

[#1924] Bug PS-248: keyring_udf mtr tests should be skipped if keyring_udf plugin is unavai

Original title:
[#1924] Bug PS-248: keyring_udf mtr tests should be skipped if keyring_udf plugin is unavailable

plugin is unavailable

Added a check file have_keyring_udf_plugin.inc that makes a test
skip itself in case keyring_udf plugin is not available. This check
file was added to the begging of all keyring_udf mtr tests

==========================================

[#1961] PS-249: Decide whether full JSON parser should be used with keyring_vault

with keyring_vault

It was decided that the vault_parser.cc is enough for our
needs to parse simple responses from Vault server.

In this commit a test for parsing garbage data was added.
All tests where run under valgrind. Valgrind did not show
any memory leakage or possible problems.

==========================================

[#1981] keyring_vault.keyring_udf was leaving one key in Vault

==========================================

[#1940] Bug#1720810: after installation PS fails to run keyring_vault test suite

After building and installing Percona Server - mtr run from installation
directory fails to run keyring_vault test suite.

The fix was to copy keyring_vault test directory to installation
directory on PS install.

======================================================================================

[#1985] PS-256: keys created by keyring_vault MTR tests are not removed from Vault server

Vault server

This fix changes how keys are removed from Vault. Instead of removing
one key after another, test:
 1) creates a mount point before running the tests.
 2) run actual test (which creates/removes keys in/from mount point
    created in step 1
 3) removes the mount point created in step 1

======================================================================================

[#1921] Bug: PS-247 - keyring_vault mtr tests should be skipped if Vault server is unavailable

Added check file is_vault_server_up.inc. This script checks if
Hashicorp Vault server that is to be used in a test is available. In
case it is not the test will be skipped. This test file was included in
all keyring_vault's MTR tests.

======================================================================================

[#2123] BLD-933: CMake option to force build and fail it if the library is not found

Adds a new cmake variable WITH_KEYRING_VAULT. Allowed values are:
ON,1,OFF,0

When cmake is run with -DWITH_KEYRING_VAULT=ON and compilation of
keyring_vault plugin is not possible, cmake aborts. Setting
WITH_KEYRING_VAULT to ON and providing CURL library which depends on
RTMP library will cause keyring vault unitest to not be build, but
overall cmake configuration will not be aborted. A warning message will
be generated.

=========================================================================

[g6]PS-269 (Initial Percona Server 8.0.12 tree)

Trivial testsuite updates

=========================================================================

[#2941] Fix PS-5328 (fil0crypt.h:123:7: error: 'memset_s' was not declared in this scope on illumos)

memset_s in C11 is only guaranteed to be available if
__STDC_LIB_EXT1__ is defined by the implementation and if user defines
__STDC_WANT_LIB_EXT1__, which we didn't do. Thus add the latter define
to CMake default defines, before the feature checks.

==========================================

PS-5363 (Merge MySQL 8.0.17): fixed gcc-9 and clang-8 build issues

==========================================

PS-5363 (Merge MySQL 8.0.17): Fixed regression introduced in gcc-9 fix

==========================================

[#3499] PS-6052: gcc 9.2.1 reports new warnings

==========================================

PS-5363 (Merge MySQL 8.0.17): Code reformatting

Code reformatted with 'clang-format-8'.

==========================================

[residual] [final-parity] Land the resolution content of the skipped merge commit

Source index 4, 992ef638537c "PS-5363 (Merge MySQL 8.0.17): Merging
mysql-8.0.17", is a merge commit and could not be plain-cherry-picked under
HR-1; it was skipped by engineer decision and ledgered as a no-output
exception.

That commit is an evil merge: it carries content present in neither parent.
storage/innobase/include/ut0mutex.h is the clearest case -
ib_uninitialized_mutex_t appears 8 times in 992ef638537c and 0 times in both
629210cc8486 and mysql-8.0.17.

61 residual paths whose content at 992ef638537c is already byte-identical to
merge-8.0.17 are taken from that commit here - from the skipped source-range
commit, not from the reference branch. The five OpenSSL 3 / RocksDB bridge
paths are deliberately excluded; they are handled by reverting the toolchain
commit at the end.

==========================================

[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyrin

Original title:
[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyring_vault unit tests unconditionally)

https://jira.percona.com/browse/PS-4757

This check used to make sense only on Ubuntu Xenial, Fedora 28, Debian 8
and Debian 9 with buggy linker.
Fixing by backporting patches from 8.0 and extending them for Denian
distros.

Bug #29471723 "BROKEN BUILD FEDORA 28, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@304dfe8)
Bug #30594413 "BROKEN BUILD ON UBUNTU 16 32 BIT, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@2a45759)

==========================================

[final-parity] mysql-test

MTR reconciliation against merge-8.0.20:

- move the log_encrypt_7 and table_encrypt_6 bodies into
  mysql-test/include/*.inc and add the _mk / _rk wrappers;
- add the dblwr_file_count test and the log_encrypt_7 result files;
- drop the six -master.opt files merge-8.0.20 does not carry;
- extend innodb_parallel_doublewrite_path_basic.test with the
  deprecation-warning check;
- counter, .inc and .result drift across the suites.

Files folded in from that commit:
  mysql-test/include/table_encrypt_4.inc
  mysql-test/include/table_encrypt_5.inc
  mysql-test/suite/innodb/r/table_encrypt_2.result
  mysql-test/suite/innodb/r/table_encrypt_4.result
  mysql-test/suite/innodb/t/table_encrypt_5.test

==========================================

[#3883] PS-5741: Incorrect use of memset_s in keyring_vault.

Fixed the usage of memset_s. The arguments should be:
void memset_s(void *dest, size_t dest_max, int c, size_t n)
where the 2nd argument is size of buffer and the 3rd is
argument is character to fill.

==========================================

[#4343] PS-7734: Fix Wshadow-field build error in keyring_vault-test

https://jira.percona.com/browse/PS-7734
(cherry picked from commit 361ed8e7cfa12952be5354228961bf6865bf87ce)

======================================================================================

[keyring_vault] Bug: PS-264 handle_fatal_signal (sig=11) in keyring::Vault_curl::write_key

Original title:
[keyring_vault] Bug: PS-264 handle_fatal_signal (sig=11) in keyring::Vault_curl::write_key | plugin

Original title:
[#2064] Bug: PS-264 handle_fatal_signal (sig=11) in keyring::Vault_curl::write_key | plugin/keyring_vault/vault_curl.cc:256

keyring::Vault_curl::write_key | plugin/keyring_vault/vault_curl.cc:256

The problem itself was in CURL library, sometimes it fails to
re-initialize CURL session properly. The CURL documentation is vague in
describing the issue. The fix was to reinitialize curl session per
every operation and do not try to reuse the existing curl session.

Also both keyrings (keyring_file and keyring_vault) export a lot of
variables. Scope of those variables were limited to library scope. This
should guard against any dynamic linking problems when both keyrings
get installed on PS.

======================================================================

[#2070] Fix bug 1741647 (5.7.20-19 build error on macOS)

macOS build has been broken by
1) memset_s use has been introduced in core server with incorrect
CMake portability check
2) keyring_vault and keyring_file symbol visibility has been limited
with a version script, which is not supported by macOS linker.

The first issue is fixed trivially, the second one by limiting the
version script use to Linux, if no sanitizers are enabled, to match
the existing behavior in libmysql.

=========================================================================

[g6]PS-269 (Initial Percona Server 8.0.12 tree)

Trivial testsuite updates

=========================================================================

[#3123] PS-5537 : Installation of 'keyring_vault' test for Centos6

- Moved CMake test suite install directives before all checks to build or not
  to ensure tests are always installed regardless if the plugin is built or not.

======================================================================================

[#2062] Bug: PS-283: keyring_vault is too quiet when plugin installation succedes, but keyring_vault is not operational

succedes, but keyring_vault is not operational

When keyring_vault is installed with use of install statement : INSTALL
PLUGIN (...) there is no feedback to the user
that keyring_vault_config_file may still need to be set. Currently when
user install the plugin he might gets the following response:

mysql> install plugin keyring_vault soname 'keyring_vault.so';
Query OK, 0 rows affected (0.02 sec)

And in server log there are these error messages:
[ERROR] Plugin keyring_vault reported: 'Could not open file with
credentials.'
[ERROR] Plugin keyring_vault reported: 'keyring_vault initialization
failure. Please check that the keyring_vault_config_file points to
readable keyring_vault configuration file. Please also make sure Vault
is running and accessible. The keyring_vault will stay unusable until
correct configuration file gets provided.'

The fix is to change this behavior so the user recieved warnings when
keyring_vault is not operational due to problem
with accessing configuration file (the path to configuration file is
stored in keyring_vault_config_file variable) - after
plugin has been installed with INSTALL PLUGIN SQL statement.

=========================================================================

PS-269 (Initial Percona Server 8.0.12 tree)

Trivial testsuite updates

=========================================================================

[#2068] PS-298: keyring_vault's timeout should be configurable

This patch adds keyring_vault_timeout variable. With use of this
variable user can control the timeout of keyring_vault - Vault server
connection [expressed in seconds]. The default value is 15s, the minimal
is 1s and maximal is 86400s (24 hours). The timeout can be disabled
by setting keyring_vault_timeout to 0.

=========================================================================

[#2095] PS-2414: keyring_vault timeout MTR tests always producing warnings

Suppressed warning "File '' not found". This is a correct warning
generated when keyring_vault is loaded without correct path to
configuration file. In this case the path is null, i.e. ''.

=========================================================================

[#2097] PS-2414: keyring_vault timeout MTR tests always producing warnings

Suppressed warning "File '' not found". This is a correct warning
generated when keyring_vault is loaded without correct path to
configuration file. In this case the path is null, i.e. ''.

(fix for keyring_vault_timeout)

===============================================

[keyring_vault] PS-269: Fix MTR --suite=keyring_vault

===============================================

[#2553] PS-269: Fix MTR --suite=keyring_vault

Warning: Tests that return `Seems that Hashicorp Vault testing server is down` are not fixed.

1. Change `plugin/keyring_vault/tests/mtr/plugin.defs` to 8.0 format
2. Fix `is_vault_server_up.inc` to work with fail-check-testcases
3. Add missing `plugin_registry_service` symbol to `plugin/keyring_vault/keyring_vault.version`
4. Adapt add_suppression to 8.0 error log format and record again MTR tests
5. Add missinf deinit_logging_service_for_plugin` to`keyring_vault_deinit`

=========================================================================

PS-269 (Initial Percona Server 8.0.12 tree)

Trivial testsuite updates

==========================================

[final-parity] rpl_key_rotation.test: 8.0.26+ wording of the "replica coordinator and
worker threads are stopped" suppression

Folded from the [final-parity] reconciliation with merge-8.0.33
(d0aabe16036f).

==========================================

[final-parity] mysql-test

MTR reconciliation against merge-8.0.20:

- move the log_encrypt_7 and table_encrypt_6 bodies into
  mysql-test/include/*.inc and add the _mk / _rk wrappers;
- add the dblwr_file_count test and the log_encrypt_7 result files;
- drop the six -master.opt files merge-8.0.20 does not carry;
- extend innodb_parallel_doublewrite_path_basic.test with the
  deprecation-warning check;
- counter, .inc and .result drift across the suites.

The mysql-test/suite/rocksdb* part of this change is split out into the
[g4] commit of the same name, promoted to GROUP 4.

==========================================

[#4033] PS-7317: Wrong parameter "explicit_default_wait_counter" in "innodb.tablespace_encr

Original title:
[#4033] PS-7317: Wrong parameter "explicit_default_wait_counter" in "innodb.tablespace_encrypt_*"

This patch:
1. Backports `wait_counter` and `explicit_default_counter` parameters for `include/wait_until_connected_again.inc` from PS-8.0.
2. Adds `explicit_default_counter=10000` to `innodb.tablespace_encrypt_*` MTR tests to make them more stable under heavy load (this was already done in PS-8.0).
3. Fixes occurrences of `explicit_default_wait_counter` with `explicit_default_counter` as `include/wait_until_connected_again.inc` uses the `explicit_default_counter` parameter, not `explicit_default_wait_counter`.

Upstream Bug: https://bugs.mysql.com/100853

Split of 6949ccf2a2352ae4ed7caf3960d378adb0cf2d01: 15 path(s) promoted to group 5; 20 path(s) deferred (unsafe hunk overlap with later group).

==========================================

[final-parity] Reconcile MTR and keyring_vault test fixtures with merge-8.0.23

Narrow reviewed hunks:
- $explicit_default_counter renamed to $explicit_default_wait_counter in the
  innodb and keyring_vault table/tablespace encryption tests, auth_sec.keyring_udf
  and dd_schema_definition_debug.
- all_persisted_variables: 467 -> 468 persisted variables (.test and .result).
- disabled.def: drop the two rpl_semi_sync_*_commit_deadlock entries.
- include/table_encrypt_1.inc: require have_punch_hole.
- include/table_encrypt_debug.inc: two extra keyring warning suppressions.
- innodb.check_ibd_filesize_16k: re-recorded compressed sizes.
- innodb.discard_tablespace: innodb_system sorts after the per-table space.
- main.mysql_config_editor: Percona copyright year 2021.
- perfschema processlist_load.inc: replace Rows_sent/Rows_examined columns.
- rocksdb.index_merge_rocksdb2: drop the duplicate flush statement.
- rpl_log_info_repository_persistence_assign_gtids_to_anonymous_transactions:
  SOURCE/REPLICA terminology.
- new sys_vars.innodb_semaphore_wait_timeout_debug_basic test for the sysvar
  registered in ha_innodb.cc.

Split of ed290c8b067821249c7da0b5a580f87d2d8e87b7: 23 path(s) promoted to group 5; 18 path(s) deferred (patch probe conflicted).

==========================================

[g6][final-parity] Keyring message wording: drop the word "plugin"

The reference rewords the keyring diagnostics from "keyring plugin" to
"keyring" (keyring became a component in this series), in
share/messages_to_clients.txt and share/messages_to_error_log.txt, and
re-records the 63 MTR fixtures that match on those strings.

Also folded into the same fixture set, because they touch the same files:
innodb_redo_log_encrypt is a MYSQL_SYSVAR_ENUM in both trees, so it displays
as ON/OFF rather than 1/0 - the recorded 1/0 values were stale; one added
Warnings: block; CHANGE MASTER -> CHANGE REPLICATION SOURCE in
rpl_key_rotation; and trailing-whitespace cleanups in table_encrypt_5.

==========================================

[g5] [#4954] PS-8337: Remove keyring encryption

This is a single commit that removes the old keyring encryption code.

[#4954] PS-8337: Remove remaining system key encryption parts

These were already present on 5.7, and were missed during the work
based on the linear branch.

[#4972] PS-8337 postfix: remove system key keyring vault unittests

These depend on a now removed feature and fail

[#4977] PS-8337 postfix: remove unused files

1. Remove unused `include/keyring_encryption_key_info.h`
2. Revert some changes in `share/messages_to_error_log.txt` to upstream

PS-8422: Merge MySQL 8.0.31 (remove unused encryption related code)

https://jira.percona.com/browse/PS-8422

==========================================

[#5129] PS-8854: Converting keyring_vault to component

https://jira.percona.com/browse/PS-8854

==========================================

[#5129] PS-8854: Fixed hanging component_keyring_vault tests under ASan

https://jira.percona.com/browse/PS-8854

For some reason 'curl' utility that is used to create mounts in
Hashicorp Vault server hangs when run under Address Sanitizer (both
from GCC and Clang).

Fixed by adding 'LD_PRELOAD= ' to the 'curl' utility invocations in
the 'mount_point_service.inc'.

Absorbed into this commit: mysql-test/suite/component_keyring_vault/inc/mount_point_service.inc

==========================================

[#5221] PS-8979: Merge MySQL 8.2.0 (reduce combinations used for component_keyring_vault tests)

https://jira.percona.com/browse/PS-8979

Run only one component_keyring_vault.load test with all 12 combinations.
Remaining tests run only with mount-v1 and mount-v2 combinations.

Split of a376746502a347abe573c7ad719d735e20c8678c: 3 path(s) held back from group 5 (patch probe conflicted); the remaining 1 path(s) were promoted to group 5.

==========================================

[#5387] PS-9218: Merge MySQL 8.4.0 (fix component_keyring_vault tests)

https://perconadev.atlassian.net/browse/PS-9218

==========================================

[#5342] PS-9165 postfix: Product Usage Tracking - phase 1 (MTR KV fixes) (#5342)

https://perconadev.atlassian.net/browse/PS-9165

'keyring_vault.keyring_udf' MTR test case modified so that it could be run
on a server built both with and without telemetry component
('-DWITH_PERCONA_TELEMETRY=ON' CMake option).

(cherry picked from commit f43c48db0100e334a5e08dd4d13e80e7dd6c0edf)

==========================================

Implemented PS-9389 (Merge MySQL 9.0.1) - conflicts solved (the rest)