[keyring_vault] New plugin: keyring_vault
Original title:
[#1852] New plugin: keyring_vault

Blueprint:
https://blueprints.launchpad.net/percona-server/+spec/keyring-vault

Plugin for storing, removing and fetching keys from Hashicorp Vault.

MTR keyring tests were refactored so they could be used with different
keyring plugins, in this particular case with keyring_vault.

New unit tests test suite for keyring_vault were added.

Plugin requires CURL library in order to build.

==========================================

[#1924] Bug PS-248: keyring_udf mtr tests should be skipped if keyring_udf plugin is unavai

Original title:
[#1924] Bug PS-248: keyring_udf mtr tests should be skipped if keyring_udf plugin is unavailable

plugin is unavailable

Added a check file have_keyring_udf_plugin.inc that makes a test
skip itself in case keyring_udf plugin is not available. This check
file was added to the begging of all keyring_udf mtr tests

==========================================

[#1961] PS-249: Decide whether full JSON parser should be used with keyring_vault

with keyring_vault

It was decided that the vault_parser.cc is enough for our
needs to parse simple responses from Vault server.

In this commit a test for parsing garbage data was added.
All tests where run under valgrind. Valgrind did not show
any memory leakage or possible problems.

==========================================

[#1981] keyring_vault.keyring_udf was leaving one key in Vault

==========================================

[#1940] Bug#1720810: after installation PS fails to run keyring_vault test suite

After building and installing Percona Server - mtr run from installation
directory fails to run keyring_vault test suite.

The fix was to copy keyring_vault test directory to installation
directory on PS install.

======================================================================================

[#1985] PS-256: keys created by keyring_vault MTR tests are not removed from Vault server

Vault server

This fix changes how keys are removed from Vault. Instead of removing
one key after another, test:
 1) creates a mount point before running the tests.
 2) run actual test (which creates/removes keys in/from mount point
    created in step 1
 3) removes the mount point created in step 1

======================================================================================

[#1921] Bug: PS-247 - keyring_vault mtr tests should be skipped if Vault server is unavailable

Added check file is_vault_server_up.inc. This script checks if
Hashicorp Vault server that is to be used in a test is available. In
case it is not the test will be skipped. This test file was included in
all keyring_vault's MTR tests.

======================================================================================

[#2123] BLD-933: CMake option to force build and fail it if the library is not found

Adds a new cmake variable WITH_KEYRING_VAULT. Allowed values are:
ON,1,OFF,0

When cmake is run with -DWITH_KEYRING_VAULT=ON and compilation of
keyring_vault plugin is not possible, cmake aborts. Setting
WITH_KEYRING_VAULT to ON and providing CURL library which depends on
RTMP library will cause keyring vault unitest to not be build, but
overall cmake configuration will not be aborted. A warning message will
be generated.

=========================================================================

[g6]PS-269 (Initial Percona Server 8.0.12 tree)

Trivial testsuite updates

=========================================================================

[#2941] Fix PS-5328 (fil0crypt.h:123:7: error: 'memset_s' was not declared in this scope on illumos)

memset_s in C11 is only guaranteed to be available if
__STDC_LIB_EXT1__ is defined by the implementation and if user defines
__STDC_WANT_LIB_EXT1__, which we didn't do. Thus add the latter define
to CMake default defines, before the feature checks.

==========================================

PS-5363 (Merge MySQL 8.0.17): fixed gcc-9 and clang-8 build issues

==========================================

PS-5363 (Merge MySQL 8.0.17): Fixed regression introduced in gcc-9 fix

==========================================

[#3499] PS-6052: gcc 9.2.1 reports new warnings

==========================================

PS-5363 (Merge MySQL 8.0.17): Code reformatting

Code reformatted with 'clang-format-8'.

==========================================

[residual] [final-parity] Land the resolution content of the skipped merge commit

Source index 4, 992ef638537c "PS-5363 (Merge MySQL 8.0.17): Merging
mysql-8.0.17", is a merge commit and could not be plain-cherry-picked under
HR-1; it was skipped by engineer decision and ledgered as a no-output
exception.

That commit is an evil merge: it carries content present in neither parent.
storage/innobase/include/ut0mutex.h is the clearest case -
ib_uninitialized_mutex_t appears 8 times in 992ef638537c and 0 times in both
629210cc8486 and mysql-8.0.17.

61 residual paths whose content at 992ef638537c is already byte-identical to
merge-8.0.17 are taken from that commit here - from the skipped source-range
commit, not from the reference branch. The five OpenSSL 3 / RocksDB bridge
paths are deliberately excluded; they are handled by reverting the toolchain
commit at the end.

==========================================

[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyrin

Original title:
[g8][#3703] Fixed PS-4757 (Consider removing CHECK_IF_CURL_DEPENDS_ON_RTMP and build keyring_vault unit tests unconditionally)

https://jira.percona.com/browse/PS-4757

This check used to make sense only on Ubuntu Xenial, Fedora 28, Debian 8
and Debian 9 with buggy linker.
Fixing by backporting patches from 8.0 and extending them for Denian
distros.

Bug #29471723 "BROKEN BUILD FEDORA 28, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@304dfe8)
Bug #30594413 "BROKEN BUILD ON UBUNTU 16 32 BIT, UNDEFINED REFERENCE TO SYMBOL '__BSS_START'"
(commit mysql/mysql-server@2a45759)

==========================================

[final-parity] mysql-test

MTR reconciliation against merge-8.0.20:

- move the log_encrypt_7 and table_encrypt_6 bodies into
  mysql-test/include/*.inc and add the _mk / _rk wrappers;
- add the dblwr_file_count test and the log_encrypt_7 result files;
- drop the six -master.opt files merge-8.0.20 does not carry;
- extend innodb_parallel_doublewrite_path_basic.test with the
  deprecation-warning check;
- counter, .inc and .result drift across the suites.

Files folded in from that commit:
  mysql-test/include/table_encrypt_4.inc
  mysql-test/include/table_encrypt_5.inc
  mysql-test/suite/innodb/r/table_encrypt_2.result
  mysql-test/suite/innodb/r/table_encrypt_4.result
  mysql-test/suite/innodb/t/table_encrypt_5.test

==========================================

[#3883] PS-5741: Incorrect use of memset_s in keyring_vault.

Fixed the usage of memset_s. The arguments should be:
void memset_s(void *dest, size_t dest_max, int c, size_t n)
where the 2nd argument is size of buffer and the 3rd is
argument is character to fill.

==========================================

[#4343] PS-7734: Fix Wshadow-field build error in keyring_vault-test

https://jira.percona.com/browse/PS-7734
(cherry picked from commit 361ed8e7cfa12952be5354228961bf6865bf87ce)