[cmake] Fix gcc/clang build issues
[#3500] PS-6054: clang 5.0.1 reports "missing-braces" warnings

==========================================

[g7][#3504] PS-6057: Suppress gcc and clang warnings for RocksDB and TokuDB

==========================================

[#3528] PS-6058: gcc 5.5.0 compilation warnings for router

Fixed:
1.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc: In function ‘constexpr int o11x_version(TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_context.cc:99:57: error: expression ‘<throw-expression>’ is not a constant-expression
       throw std::invalid_argument("version out of range");
```
2.
```
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc: In constructor ‘TlsServerContext::TlsServerContext(TlsVersion, TlsVersion)’:
/data/mysql-server/mysql-8.0/router/src/http/src/tls_server_context.cc:67:43: error: statement has no effect [-Werror=unused-value]
   SSL_CTX_set_ecdh_auto(ssl_ctx_.get(), 1);
```

==========================================

[#360] Add FORTIFY_SOURCE=2 definition in cmake for release builds

==========================================

[split] build flag list whitespace (CMakeLists.txt)

Split out of the following commit, which bundled three unrelated
one-line post-merge fixes with three different owners:

[compilation] dCompilation/test fixes for 8.0.13 merge, #2

===============================================

[#2756] dCompilation/test fixes for 8.0.13 merge, #2

* Added a missing whitespace to a build flag list
* Fixed mtr test suite list
* Fixed a typo in a unit test

===============================================

[#2249] PS-3887: Move perfschema to the beginning of the storage list in CONFIGURE_PLUGINS

[#2133] PS-3793: added osx travis config

* Added OSX to the build matrix.
* Fixed issues with older bash versions on OSX.
* Made maintainer_mode optional, as the OSX build results in some warnings, and fixing them would take time.
  As it's not an officially supported platform, warnings are ok for now.
* Made tokudb optional, as the OSX build doesn't support it

(cherry picked from commit 185b61405d80a6c8af12081a1e42677299746b74)
(cherry picked from commit 64cfbf3b99c337a8ffdd39641a1efeda4db95726)

======================================================================

[#2240] PS-3899: silence an uninitialized read in zlib

According to the library developers, this is an optimization which while reads these bytes, doesn't use them for anything, and should be ignored.

(cherry picked from commit 2096be4b643e2047fa33c2dbd12c73d820fdae18)
(cherry picked from commit 43f99a0eacd2a6e0271482d79e544c9d518268d6)

==========================================

[g8]PS-5363 (Merge MySQL 8.0.17): added missing parameter in MY_SANITIZER_CHECK for MSAN

==========================================

[#2075] lp-1738171: Show compiler output when the ABI check fails

Changes in do_abi_check.cmake were made to have the ability to see
compilator output on compilation error.

Split out of "[#2075] lp-1738171: Build error on FreeBSD with 5.6.38-83.0".

(cherry picked from commit cf8bfa4ef1fcd90596cdcfda1146231cd2e8a124)

==========================================

PS-8865: Set minimal compiler requirements to GCC 8.1 or Clang 6

==========================================

[#5286] PS-9188: Fix clang-18 compilation issues

1. Boost issues:
```
In file included from /data/mysql-server/percona-8.0/sql/gis/line_interpolate.cc:29:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/geometry.hpp:17:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/geometry/geometry.hpp:53:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/geometry/core/radian_access.hpp:26:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/numeric/conversion/cast.hpp:33:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/numeric/conversion/converter.hpp:13:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/numeric/conversion/conversion_traits.hpp:13:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/numeric/conversion/detail/conversion_traits.hpp:18:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/numeric/conversion/detail/int_float_mixture.hpp:19:
In file included from /data/mysql-server/_deps/boost_1_77_0/boost/mpl/integral_c.hpp:32:
/data/mysql-server/_deps/boost_1_77_0/boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'udt_builtin_mixture_enum' [-Wenum-constexpr-conversion]
   73 |     typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
      |                               ^
/data/mysql-server/_deps/boost_1_77_0/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |
```

2. Issues with stdc++ library from gcc-13:

```
In file included from /data/mysql-server/percona-8.0/libbinlogevents/src/compression/none_comp.cpp:23:
In file included from /data/mysql-server/percona-8.0/libbinlogevents/include/compression/none_comp.h:26:
In file included from /data/mysql-server/percona-8.0/libbinlogevents/include/compression/compressor.h:27:
In file included from /data/mysql-server/percona-8.0/libbinlogevents/include/compression/base.h:26:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/string:54:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/basic_string.h:39:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ext/alloc_traits.h:34:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/alloc_traits.h:266:8: error: 'construct<mysqlns::buffer::Buffer_view<>, mysqlns::buffer::Buffer_view<>>' is deprecated: std::allocator::construct is deprecated in C++17 [-Werror,-Wdeprecated-declarations]
  266 |         { __a.construct(__p, std::forward<_Args>(__args)...); }
      |               ^
/data/mysql-server/percona-8.0/libbinlogevents/include/resource/allocator.h:139:5: note: 'construct<mysqlns::buffer::Buffer_view<>, mysqlns::buffer::Buffer_view<>>' has been explicitly marked deprecated here
  139 |   [[deprecated("std::allocator::construct is deprecated in C++17")]] void
      |     ^
```

==========================================

[#5387] PS-9218: Merge MySQL 8.4.0 (fix gcc-14 build)

https://perconadev.atlassian.net/browse/PS-9218

==========================================

PS-9745: Code refresh for 9.3.0-1 (disable gcc-10 as it's no longer supported)

==========================================

PS-9745: Code refresh for 9.3.0-1 (disable clang-14 and clang-15 as they are no longer supported)

==========================================

PS-11142: Fix GCC 16 compilation issue in mysql_concurrency_server

https://perconadev.atlassian.net/browse/PS-11142

Problem:
The RelWithDebInfo build with GCC 16 (-Werror) fails on
libs/mysql/concurrency/condition_variable_wrapper.cpp:

  include/mysql/psi/mysql_cond.h:145:41: error: '<unknown>' may be used
  uninitialized [-Werror=maybe-uninitialized]
    145 |   that->m_psi = PSI_COND_CALL(init_cond)(key, &that->m_cond);
  note: by argument 2 of type 'const void*' to
  'PSI_cond*(PSI_cond_key, const void*)'

inline_mysql_cond_init() hands &that->m_cond to the performance schema as
a const void* identity token before native_cond_init() writes it, so the
callee never reads through the pointer. GCC 16's -O2 analysis cannot see
that and warns when the helper is inlined into the
mysql::concurrency::Condition_variable_wrapper constructor. The library is
new in the mysql-26.7.0 code refresh, which is why the warning only
appears now.

Fix:
Add a per-file -Wno-maybe-uninitialized for condition_variable_wrapper.cpp
in libs/mysql/concurrency/CMakeLists.txt, guarded by GCC >= 16. This is the
same suppression PS-11142 already applies to the identical PSI-inlining
pattern in the xpl::Cond / xpl::RWLock constructors (plugin/x) and in
myrocks::Rdb_cond_var / Rdb_mutex (storage/rocksdb); -Wmaybe-uninitialized
is emitted late in the optimization pipeline, so a per-file flag is the
dependable suppression.

The sibling Mutex_wrapper constructor in the same library does not trigger
the warning and is left alone.

Verified with a full gcc-16 RelWithDebInfo build (WITH_ROCKSDB=ON):
0 errors, 0 warnings. No MTR run.