[keyring_system_keys] PS-3779: System key rotation support in keyring framework
Keyring framework should be capable of rotating system keys. This
feature is needed by different encryption components (binlog encryption,
rotation-enabled tablespaces). Please note, that by system key we mean
all system keys that starts with a prefix percona_ , for instance:
percona_binlog). This feature does not extend keyring framework API, but
adds new functionalities to existing API functions:

 - calling my_key_generate or my_key_store with system key id will
   create rotation-enabled system key in keyring. (For instance calling
   my_key_generate("percona_binlog", "AES", NULL, 16) will add key
   percona_binlog:0 to keyring. The ':0' part of the system key id is the
   version assigned to the key).
 - calling my_key_generate or my_key_store with existing system key id
   will rotate the key to a new version. (for instance percona_binlog:0
   exist in keyring, calling my_key_generate("percona_binlog", "AES", NULL,
   16) will add key percona_binlog:1 to the keyring)
 - calling my_key_fetch with system key id will fetch the latest
   version of the system key. For instance if there are two keys in the
   keyring percona_binlog:0 and percona_binlog:1 -
   my_key_fetch("percona_binlog" (...)) will fetch percona_binlog:1
 - calling my_key_remove on system key will result in error - as it is
   not possible to remove system key from keyring (at least not from
   keyring API)

Implementation of this feature needs to support binlog key rotation.
This, apart from extending the keyring framework also includes providing:
 - rotate_system_key function. With this function super users will be
   capable of rotating binlog key, by calling
   rotate_system_key("percona_binlog"). As mentioned, users will need to
   have super privilege to be able to rotate the key.
 - binlog encryption should be extended - so it would be capable of
   working with different versions of percona_binlog system key

Implementation of this feature also includes a convenience function
parse_system_key that helps to separate key id and key version from
system key data.

==========================================
[#2185] PS-3848: macOS build broken, undefined symbol __db_keyword_, referenced from binary

Original title:
[#2185] PS-3848: macOS build broken, undefined symbol __db_keyword_, referenced from binary_log::Log_event_header::Log_event_header

from binary_log::Log_event_header::Log_event_header

binlog_event.cpp as a part of libbinlogevent should not depend on
mtr debug variables and thus on my_dbug.h. Created
binary_log_debug::debug_expect_unknown_event variable which value
depends on the value of mtr debug variable expect_Unknown_event.
This is the correct way to make binlog_event.cpp not depend on
my_dbug.h

==========================================

[#2415] PS-4519: system_keys_container.cc:128:146: error: no matching function for call to

Original title:
[#2415] PS-4519: system_keys_container.cc:128:146: error: no matching function for call to 'make_pair...'

for call to 'make_pair...'

Got rid of template specification so rvalue could be deduced by
make_pair.

=========================================================================

[g6]PS-269 (Initial Percona Server 8.0.12 tree)

Trivial testsuite updates

==========================================

PS-269 (Initial Percona Server 8.0 tree)

Fix merge error that broke IO_CACHE. Make my_b_inited return bool
instead of int at the same time.

==========================================

[keyring_system_key_rotation] PS-4728: ASan: heap-buffer-overflow in Keyring_api_test.GeneratePBRotatePBFetchFirs

===============================================
[#2767] PS-4728: ASan: heap-buffer-overflow in Keyring_api_test.GeneratePBRotatePBFetchFirs

Original title:
[#2767] PS-4728: ASan: heap-buffer-overflow in Keyring_api_test.GeneratePBRotatePBFetchFirstVersionFetchLatestPB unit test

Keyring_api_test.GeneratePBRotatePBFetchFirstVersionFetchLatestPB unit
test

In test GeneratePBRotatePBFetchFirstVersionFetchLatestPB there is a
comparison of keys' data retrieved first by specifying key with version
percona_binlog:0 and next by specifying just percona_binlog (latest
key). Since there was a key rotation those operations should retrieve different keys.
The second key apart from key's data should also contain key's
version. The first one should not - before the fix the key version was
also skipped in the first key and thus there was ill memory access.

==========================================

[split] encrypted IOCACHE C++11-ification (mysys/mf_iocache.cc)

Split out of the following commit, which bundled three changes with
three different owners:

[io_cache_refactor] PS-5108 (Assertion `info->read_pos == info->read_end' failed | size_t my_b_fill(IO_

===============================================
[#2788] PS-5108 (Assertion `info->read_pos == info->read_end' failed | size_t my_b_fill(IO_

Original title:
[#2788] PS-5108 (Assertion `info->read_pos == info->read_end' failed | size_t my_b_fill(IO_CACHE*))

Fix a regression from 8.0.13 merge where newly-introduced
IO_CACHE_binlog_cache_storage (WL#10956) always calls my_b_fill for
reinited cache instead of consuming the in-memory buffer first,
whereas the encrypted cache expects the in-memory buffer to be
consumed before any read.

Fix by returning the IO_CACHE memory buffer contents, whenever they
are available, instead of doing the I/O. The alternative was to change
the IOCACHE code to support reads without used up memory buffer, but
this would be less efficient too.

At the same time do minor C++11'ification for the encrypted IOCACHE
code.

Re-record main.read_only_persisted_plugin_variables, which was also
affected by this bug.

==========================================

[#3109] PS-5243 SHOW BINLOG EVENT ASSERTION

Cherry-pick the testcase[1] from 5.7 and fixed the bug itself:
Executing SHOW BINLOG EVENT from an invalid position
could result in a segmentation fault on 32bit machines.
my_b_read would try to evaluate info->read_pos + Count
which could result on an Address out of bounds error.
This will cause my_b_read enter the if and attempt to
do a memcpy which will result in a segmentation fault.

This patch ensures that the boundaries are calculated within
the info IO_CACHE and only then evaluated with Count.

my_b_write uses the same logic as my_b_read. Extending
the patch to my_b_write as well.

mysqlbinlog was affected in the same way. This patch
also fixes mysqlbinlog.

[1]:
commit ac038cc5ed04675c90f3921bcd4c72e89979cbd2
Author: Przemek Skibinski <przemyslaw.skibinski@percona.com>
Date:   Mon Dec 24 13:11:53 2018 +0100

    PS-5126: SHOW BINLOG EVENTS FROM <bad offset> is not diagnosed
    inside Format_description_log_events

    Backport improved rpl.bug75480 test from 8.0

==========================================

PS-5363 (Merge MySQL 8.0.17): fixed gcc-9 and clang-8 build issues

==========================================

PS-5363 (Merge MySQL 8.0.17): Fixed regression introduced in gcc-9 fix

==========================================

[#3499] PS-6052: gcc 9.2.1 reports new warnings

==========================================

PS-5363 (Merge MySQL 8.0.17): Code reformatting

Code reformatted with 'clang-format-8'.

==========================================

[#3313] Implement PS-5749 (Code review fixes from 8.0 work: misc)

Backport miscellaneous fixes from 8.0 work:
- thd_flush_log_at_trx_commit: replace void* arg with THD* one;
- split ut_a / ut_ad / DBUG_ASSERT / assert / assert_always /
  assert_debug logical conjunctions to separate asserts;
- remove extra space in innodb_sched_priority_master_update warning message;
- mark lock0wait.cc:print_lock_wait_timeout static;
- ut0ut.cc: do not include btr0types.h;
- mysql_unix_socket_connect: use HAVE_PSI_FILE_INTERFACE instead of
  HAVE_PSI_INTERFACE, replace PSI_server calls  with PSI_FILE_CALL
  macro, restructure the PFS annotation to match the common style
- audit_log plugin: mark a lot of variables and functions static,
  remove unused ones;
- mark Percona additions in sql_show.cc static;
- move extern void init_log_slow_verbosity,
  init_slow_query_log_use_global_control, init_log_slow_sp_statements
  declarations from mysqld.cc to set_var.h
- mark row0mysql.cc:column_zip_set_alloc static.

==========================================

[keyring_system_key_rotation] PS-5554: System keys not thread safe

===============================================

[#3136] PS-5554: System keys not thread safe

System keys are lazy initialized. This means creating the key's body
only when it is requested. The same key can be requested by multiple
threads. Which means the initialization can be requested by multiple threads
simultaneously. To cope with this a lock-free CAS was used. The same
system key can be requested by multiple threads but only one thread
will be first and thus will set the key body.