[backup_locks] PS-4758: A sequence of LOCK TABLES FOR BACKUP and STOP SLAVE SQL_THREAD can
Original title:
[backup_locks] PS-4758: A sequence of LOCK TABLES FOR BACKUP and STOP SLAVE SQL_THREAD can cause r

===============================================

[#2832] PS-4758: A sequence of LOCK TABLES FOR BACKUP and STOP SLAVE SQL_THREAD can cause replication to be blocked and cannot be restarted normally

can cause replication to be blocked and cannot be restarted normally

When after LOCK TABLES FOR BACKUP / LOCK BINLOG FOR BACKUP slave SQL
thread is waiting for backup / binlog lock subsequent STOP SLAVE
SQL_THREAD causing deadlock. SQL thread is waiting for backup lock, STOP
SLAVE is waiting for SQL thread to complete current statement.

Fix is to throw an error when the thread which acquired the backup lock
is trying to stop slave.

==========================================

[backup_locks] PS-4758: post merge fix

===============================================

[#2846] PS-4758: post merge fix

8.0 version of the fix incorrectly determined whether the thread has
acquired LOCK INSTANCE FOR BACKUP lock. Instead it determined if the
lock has been acquired by any thread.

Fix is to use MDL_context::owns_equal_or_stronger_lock to check if
current thread owns the lock.

===============================================

[#3154] PS-5360 : Implement server side changes for XtraBackup MyRocks PS-5362 : Create new session variable rocksdb_create_temporary_checkpoint PS-5362 : Expose RocksDB WAL position through I_S.log_status PS-5563 : Create new session variable rocksdb_disable_file_deletions PS-5583 : Lock tables for backup blocks DML for RocksDB

PS-5362 : Create new session variable rocksdb_create_temporary_checkpoint
PS-5362 : Expose RocksDB WAL position through I_S.log_status
PS-5563 : Create new session variable rocksdb_disable_file_deletions
PS-5583 : Lock tables for backup blocks DML for RocksDB

- Temporarily forked RocksDB into percona/rocksdb and created temp branch
  (ps-5362) pointing to same commit that 8.0 currently points to
  (516c7df05dd267e4725e7dd061a6767de7aayyac0d).

- Cherry-picked Sergeis work onto new RocksDB branch (ps-5362) in new temp fork.

- Repointed Percona Server RocksDB git submodule commit pointer to point to new
  fork (percona/rocksdb) at same commit that was previously pointed to
  (516c7df05dd267e4725e7dd061a6767de7aayyac0d) +1 commit to Sergeis
  cherry-picked work (3f5c1236026233b34be64d597fe660d7e698f2f5).

- Added new session variable to MyRocks rocksdb_create_temporary_checkpoint
  which will create a temporary RocksDB 'checkpoint' or 'snapshot'.  If the
  session ends with an existingcheckpoint, or if the variable is reset to
  another value, the checkpoint will get removed.

- Added new session variable to MyRocks rocksdb_disable_file_deletions, which
  when set, will tell RocksDB to disable the deletion of old WAL and .sst files.
  If the session ends without re-enabling file deletion, file deletions will be
  explicitly re-enabled.

- Expose rocksdb WAL position in i_s.log_status table.

- Added tests to MyRocks for new options and behaviors.

- Added HTON_SUPPORTS_ONLINE_BACKUPS to MyRocks handlerton flags.

- Split main.backup_locks and rpl.rpl_backup_locks tests into common includes
  with engine and feature controlling options and updating to use modern
  semantics.  Implemented InnoDB and MyRocks tests based on these new common
  tests and recorded.

- Updated documentation to reflect MyRocks support/inclusion in LTFB.

==========================================

PS-5363 (Merge MySQL 8.0.17): Fix clone tests failing with Can't execute the given command

Original title:
PS-5363 (Merge MySQL 8.0.17): Fix clone tests failing with Can't execute the given command because you have active locked tables or an active transaction

The fix for PS-4758 (8.0) has multiple parts.
1. Handle LOCK TABLES FOR BACKUP;
2. Hanlde LOCK BINLOG FOR BACKUP;
3. Handle LOCK INSTANCE FOR BACKUP;

3 is reported as upstream bug https://bugs.mysql.com/bug.php?id=93649

And it is fixed by Oracle:
commit 7e75ca24a273bd2e1aaa662e6712025c4dd8e0ca
Author: Pedro Figueiredo <pedro.figueiredo@oracle.com>
Date:   Tue Apr 23 14:57:48 2019 +0100

    BUG#29386503 STOP SLAVE SQL_THREAD DEADLOCKS IF DONE WHILE HOLDING LOCK INSTANCE FOR BACKUP

Fix:
----
Our fix for 3 is un-necessary (duplicate and doesn't handle Clone). So
we revert fix for 3.

==========================================

[g6]PS-6866: Merge fb-prod201904 (8.0)

https://jira.percona.com/browse/PS-6866

==========================================

[g6][#3772] PS-6966: fix clang-10 compilation issues

1. Update PerconaFT submodule pointer to https://github.com/percona/PerconaFT/commit/ba5ca618e0a192c685afe38617c867ba81c93c66
2. Remove PerconaFT suppression for the `-Wno-address-of-packed-member` warning
3. Fix clang-10 issue:
```
/percona-5.6/storage/myisam/mi_rkey.c:189:5: error: misleading indentation; statement is not part of the previous 'else' [-Werror,-Wmisleading-indentation]
    info->set_rnext_same_key= TRUE;
```

===========================================================

[#3772] PS-6966: fix clang-10 compilation issues (mysql-8.0)

==========================================

[myrocks] [g5][final-parity] Reconcile MTR fixtures with the reference

Test-fixture differences left after the replay, in three classes:

 * Result files that source commits re-applied in their mysql-8.0.26
   form, so they lost mysql-8.0.27 output changes: the fully qualified
   `test`.`tbl`.`col` names in EXPLAIN Note 1003 (group_by, view,
   bug74778, gis/bug77580, tokudb type_*/ctype_* and the rocksdb and
   *_rpl extra-column results), the perfschema setup_threads rows and
   the backup_locks / percona_heap_blob / pool_of_threads outputs.

 * The all_persisted_variables counters, which this replay carried
   forward commit by commit and which end one higher than the reference;
   set to the reference value of 497 in both the .test and the .result.

 * Fixtures belonging to reference-range commits with no source index,
   most visibly PS-8032 (innodb.log_inplace_alter_with_exclusiv_lock),
   the coredump test, valgrind.supp and the rpl/rpl_gtid additions.

Applied as a narrow patch restricted to mysql-test/** and the plugin
tests/mtr fixtures.

Split of 5b78780e5cdd6980db12fa8cea84b1ddaabe6e3c: 23 path(s) held back from group 5 (patch probe conflicted); the remaining 20 path(s) were promoted to group 5.

==========================================

[g5][#4871] PS-8246 bug: Adapt Encryption UDF MTR test cases to OpenSSL 3.0.x

https://jira.percona.com/browse/PS-8246

Refactored Encryption UDFs MTR test cases so that they now pass on
platforms with OpenSSL 3.0.x.

'have_openssl_binary_version.inc' MTR include file extended so that
in case when '$openssl_binary_version_do_not_skip' variable is set to
non-zero, it does not skip the test but instead just reports whether the
OpenSSL library version matches the provided pattern or not via
'$openssl_binary_version_match' result variable.

Fixed how 'have_openssl_binary_version.inc' was used in some
'Encryption UDFs' MTR test cases - in some occasions
'$openssl_binary_version' variable was not defined before this file
was included.

Direct calls to '--exec openssl ...' were changed to more appropriate
'--exec $OPENSSL_EXECUTABLE ...'.

'percona_encryption_udf_digest_table.inc' reworked so that we fill the
'digest_type' table with different values based on the hash functions
available in the particular version of the OpenSSL library that
is currently in use (1.0.2 / 1.1.x / 3.0.x).

Recorded PEM-format read/write error messages generated by Encryption UDFs
functions trimmed with '--replace_regex' to just basic (defined inside
'opensslpp') messages in order to unify this output for different OpenSSL
library versions.

Split of f4bd3e64f2c5f417b5fbc93a47785f0f7608487e: 29 path(s) held back from group 5 (patch probe conflicted); the remaining 1 path(s) were promoted to group 5.

=============================================================================

[#4735] Fixed PS-8136 - LOCK TABLES FOR BACKUP is not preventing ALTER INSTANCE ROTATE INNODB MASTER KEY

https://jira.percona.com/browse/PS-8136

Problem:
Lightweight MDL LTFB should block operations that will result on
inconsistent backups. Rotating master key after the backup has started
will make tables header to point to a key that is not present on backup
cache of keys as PXB reads them once at the beginning of the backup.
Rotating the master key should be blocked.

Fix:
Enhanced Rotate_innodb_master_key to wait for up to lock_wait_timeout
seconds in case other session has acquired LTFB and also fail in case
LTFB has been acquired by the current session.