[#4713] PS-7980: Basic implementation of LDAP authorization
This patch adds the ability to provide roles from an external source to
MySQL users with authentication plugins, and adds a simple LDAP
implementation.

How it works:

We extend the authentication info structure used by authentication
plugins by one more type, which should contain role names.

During authorization, the server will automatically add these to the in
memory cache, but not to the persisted mysql database. This means that
the roles will shouw up on queries working on the cache, such as SHOW
GRANTS, but will be invisible on queries working on the persisted
database.

Another limitation is that in the current implementation, external roles
are only populated when a user logs on. Users who didn't log on since
the server was started will only show persisted roles.

If needed, both of these could be changed in the future - for example by
adding another column to the role mappings (showing that it's an
externally managed role) they could be persisted.

We could also extend the plugin API to provide additional methods for
checking external changes automatically - for example by using a
background thread.

As permissions are only important when a user actually logs in, these
were omitted from this first version.

Interaction with related SQL commands:

* FLUSH PRIVILEGES reloads the in memory cache from the persisted
  database. With this patch we also track external roles separately, and
  automatically re-add them at the same place. This way once an external
  node gets added, it will always stay visible.
* External roles are rechecked for every login. If the list changes in
  the external database,those changes will be reflected in the new
  session
* For now we allow REVOKEing external roles - but they will be readded
  automatically during the next login. Maybe it would be a better
  solution to disable REVOKE for these with an error message explaining
  that they should be removed in the external application.

==========================================

[#4988] PS-8613: Fix lock contention introduced by LDAP authorization

Issue: With the LDAP authorization implemented, all connection
requests take the ACL_lock to verify external roles. This leads
to significantly increased login times with high concurrency.

Fix: only take the lock when it's actually necessary: when the user
has external roles configured by the authentication plugin.

===========================================================================

[#5021] PS-8674 Compilation error on ARM AppleClang 14.0 https://jira.percona.com/browse/PS-8674

https://jira.percona.com/browse/PS-8674

Disabled the PERCONA_AUTHENTICATION_LDAP on APPLE ARM
because of compilation error

undefined symbols for architecture arm64:
  "_ldap_set_urllist_proc", referenced from:
ld: symbol(s) not found for architecture arm64

The problem with MacOS system libraries.